package com.drivecare.app.utils

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val displayName: String, val code: String, val isRtl: Boolean = false) {
    ENGLISH("English", "en"),
    URDU("اردو (Urdu)", "ur", isRtl = true),
    ARABIC("العربية (Arabic)", "ar", isRtl = true),
    HINDI("हिंदी (Hindi)", "hi"),
    CHINESE("简体中文 (Chinese)", "zh")
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }

object AppStrings {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> englishMap[key] ?: key
            AppLanguage.URDU -> urduMap[key] ?: englishMap[key] ?: key
            AppLanguage.ARABIC -> arabicMap[key] ?: englishMap[key] ?: key
            AppLanguage.HINDI -> hindiMap[key] ?: englishMap[key] ?: key
            AppLanguage.CHINESE -> chineseMap[key] ?: englishMap[key] ?: key
        }
    }

    private val englishMap = mapOf(
        "app_name" to "DriveCare",
        "tab_dashboard" to "Dashboard",
        "tab_garage" to "Vehicles",
        "tab_fuel" to "Fuel",
        "tab_services" to "Services",
        "tab_service" to "Services",
        "tab_more" to "More",
        "tab_documents" to "Documents",
        "tab_emergency" to "Emergency",
        "tab_achievements" to "Achievements",
        "tab_settings" to "Settings",
        "tab_reminders" to "Reminders",
        "backup_restore" to "Backup & Restore",
        
        "total_vehicles" to "Total Vehicles",
        "upcoming_services" to "Upcoming Services",
        "active_insurance" to "Active Insurance",
        "monthly_fuel_cost" to "Monthly Fuel Cost",
        "total_fuel_entries" to "Total Fuel Logs",
        "vehicle_health_score" to "Vehicle Health Score",
        
        "health_excellent" to "Excellent",
        "health_good" to "Good",
        "health_fair" to "Fair",
        "health_poor" to "Poor",
        
        "add_vehicle" to "Add Vehicle",
        "edit_vehicle" to "Edit Vehicle",
        "delete_vehicle" to "Delete Vehicle",
        "no_vehicles_title" to "No Vehicles Added Yet",
        "no_vehicles_desc" to "Tap the button below to add your first vehicle.",
        "vehicle_name" to "Vehicle Name",
        "brand" to "Brand",
        "model" to "Model",
        "year" to "Year",
        "plate_no" to "Plate No.",
        "fuel_type" to "Fuel Type",
        "odometer" to "Odometer Reading",
        "type" to "Vehicle Type",
        "fuel" to "Fuel",
        "plate" to "Plate",

        "vtype_car" to "Car",
        "vtype_motorcycle" to "Motorcycle",
        "vtype_scooter" to "Scooter",
        "vtype_bus" to "Bus",
        "vtype_van" to "Van",
        "vtype_pickup_truck" to "Pickup Truck",
        "vtype_suv" to "SUV",
        "vtype_jeep" to "Jeep",
        "vtype_taxi" to "Taxi",
        "vtype_truck" to "Truck",
        "vtype_tractor" to "Tractor",
        "vtype_trailer" to "Trailer",
        "vtype_minibus" to "Minibus",
        "vtype_rv_camper" to "RV / Camper",
        "vtype_electric_car" to "Electric Car",
        "vtype_hybrid_car" to "Hybrid Car",
        "vtype_bicycle" to "Bicycle",
        "vtype_fleet" to "Fleet",
        "vtype_other" to "Other (Custom)",
        
        "log_fuel" to "Log Fuel",
        "select_vehicle" to "Select Vehicle",
        "all_vehicles" to "All Vehicles",
        "total_spent" to "Total Spent",
        "total_quantity" to "Total Quantity",
        "litres" to "Litres",
        "cost" to "Cost ($)",
        "gas_station" to "Gas Station (Optional)",
        "no_fuel_entries" to "No fuel entries found.",
        
        "add_service_log" to "Add Service Log",
        "service_title" to "Service Title (e.g. Oil Change)",
        "workshop" to "Workshop / Garage",
        "no_service_logs" to "No Service Logs Yet",
        "no_service_desc" to "Track oil changes, repairs, and tire rotations.",
        
        "add_reminder" to "Add Reminder",
        "reminder_title" to "Reminder Title (e.g. Insurance)",
        "due_date" to "Due Date",
        "no_reminders" to "No Service Reminders",
        "no_reminders_desc" to "Set reminders for insurance renewal, oil change, or inspection.",
        
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "confirm_delete_title" to "Delete Vehicle",
        "confirm_delete_msg" to "Are you sure you want to delete this vehicle? All associated logs will be removed.",
        "change_language" to "Change Language",
        
        "overview_title" to "DriveCare Overview",
        "pending_tasks" to "Pending Tasks",
        "fuel_spent" to "Fuel Spent",
        "service_spent" to "Service Spent",
        "fleet_summary" to "Quick Fleet Summary",
        "vehicles_count" to "Vehicles",
        "no_vehicles_registered" to "No registered vehicles in garage.",
        "trip_calculator" to "Trip Cost Estimator",
        "health_score" to "Vehicle Health",
        "calculate_trip" to "Calculate Trip Cost",
        "distance_km" to "Trip Distance (km)",
        "fuel_price" to "Fuel Price / Litre ($)",
        "avg_mileage" to "Average Mileage (km/L)",
        "estimated_cost" to "Estimated Cost",
        "passengers" to "Passengers Count",
        "cost_per_person" to "Cost Per Person",
        "calculate" to "Calculate",
        
        "advisor_title" to "Smart Maintenance Advisor",
        "advisor_subtitle" to "AI-powered maintenance suggestions based on mileage and history.",
        "oil_change_due" to "Engine Oil Replacement Recommended",
        "brake_inspection_due" to "Brake Pad Inspection Due",
        "air_filter_due" to "Air Filter Replacement Needed",
        "coolant_check_due" to "Coolant Fluid Level Check",
        "battery_check_due" to "Battery Health Check",
        "tire_rotation_due" to "Tire Rotation & Balancing",
        
        "vehicle_profile" to "Vehicle Profile",
        "export_pdf" to "Generate PDF Report",
        "share_pdf" to "Share Report",
        "pdf_generated" to "PDF Report Generated Successfully",
        
        "add_document" to "Add Document",
        "doc_type" to "Document Type",
        "issue_date" to "Issue Date",
        "expiry_date" to "Expiry Date",
        "no_documents" to "No Vehicle Documents Saved",
        
        "emergency_title" to "Roadside Emergency & Assistance",
        "one_tap_call" to "One-Tap Call",
        "mechanic" to "Mechanic",
        "family" to "Family Contact",
        "insurance_hotline" to "Insurance Hotline",
        "towing_service" to "Tow Truck Service",
        "add_contact" to "Add Emergency Contact",
        "no_contacts" to "No Emergency Contacts Added",
        
        "achievements_title" to "Achievements & Milestones",
        "first_vehicle" to "Pioneer: First Vehicle Added",
        "first_fuel" to "Pit Stop: First Fuel Entry Logged",
        "first_service" to "Mechanic Apprentice: First Service Logged",
        "distance_1000km" to "Road Tripper: 1,000 KM Driven",
        "distance_5000km" to "Highway Master: 5,000 KM Driven",
        "fuel_10_entries" to "Regular Refueler: 10 Fuel Entries",
        "fuel_25_entries" to "Fuel Tracker Pro: 25 Fuel Entries",
        "fuel_50_entries" to "Fleet Captain: 50 Fuel Entries",
        
        "settings_title" to "Settings & Preferences",
        "theme_mode" to "Dark Mode Theme",
        "language" to "Application Language",
        "backup_data" to "Backup Database (JSON)",
        "restore_data" to "Restore Database",
        "notifications" to "Service Notifications",
        "about_drivecare" to "DriveCare Version 2.0.0 (Global Edition)",

        // New localization keys for complete translation
        "analytics_cost_breakdown" to "Analytics & Cost Breakdown",
        "monthly_fuel_expenditure" to "Monthly Fuel Expenditure ($)",
        "expense_category_breakdown" to "Expense Category Breakdown",
        "total_expense_logged" to "Total Expense Logged",
        "recent_timeline_activity" to "Recent Timeline Activity",
        "view_all" to "View All",
        "no_recent_activity" to "No recent activity logged yet. Refuel or log maintenance to see history.",
        "vehicles_active_fleet" to "Vehicles Active in Fleet",
        "tasks_pending" to "tasks pending",
        "all_tasks_up_to_date" to "All tasks up to date",
        "fleet_health_label" to "Fleet Health",
        "fuel_efficiency" to "Fuel Efficiency",
        "cost_label" to "Cost",

        "insurance_policies_title" to "Insurance & Policies",
        "insurance_policies_sub" to "Policy Details, Renewal Reminders & Coverage Tracking",
        "status_active" to "Active",
        "status_expiring_soon" to "Expiring Soon",
        "status_expired" to "Expired",
        "filter_all" to "All",
        "filter_expiring" to "Expiring",
        "no_policies_found" to "No Insurance Policies Found",
        "no_policies_desc" to "Tap the + button below to add your vehicle insurance policy and set renewal reminders.",
        "policy_no_prefix" to "Policy #",
        "vehicle_linked" to "Vehicle Linked",
        "coverage_type" to "Coverage Type",
        "premium" to "Premium",
        "valid_period" to "Valid",
        "auto_renew_on" to "Auto-Renew On",
        "btn_renew" to "Renew",
        "btn_agent" to "Agent",
        "add_policy_title" to "Add Insurance Policy",
        "edit_policy_title" to "Edit Insurance Policy",
        "provider_name" to "Insurance Provider Name",
        "policy_number" to "Policy Number",
        "start_date" to "Start Date",
        "agent_phone" to "Agent Phone / Hotline",
        "notes_info" to "Notes / Deductible Info",
        "enable_autorenew" to "Enable Auto-Renew Flag",
        "save_policy" to "Save Policy",
        "update_policy" to "Update Policy",
        "renew_policy_title" to "Renew Policy #",
        "new_start_date" to "New Start Date",
        "new_expiry_date" to "New Expiry Date",
        "renewal_premium" to "Renewal Premium Amount",
        "confirm_renewal" to "Confirm Renewal & Log Expense",
        "delete_policy_title" to "Delete Insurance Policy",

        "expense_manager_title" to "Expense Manager",
        "expense_manager_sub" to "Track Parking, Tolls, Taxes, Insurance & Repairs",
        "total_vehicle_expenses" to "Total Vehicle Expenses",
        "category_breakdown" to "Category Breakdown",
        "expense_history" to "Expense History",
        "no_expenses_found" to "No Expenses Logged Yet",
        "no_expenses_desc" to "Tap '+ Add Expense' to log parking, tolls, taxes, or insurance.",
        "add_expense" to "Add Expense",
        "log_new_expense" to "Log New Expense",
        "expense_title" to "Expense Title",
        "category" to "Category",
        "amount" to "Amount",
        "date" to "Date",

        "timeline_title" to "Vehicle Timeline",
        "timeline_sub" to "Chronological Activity Stream Across Refills, Services & Expenses",
        "no_timeline_found" to "No Timeline Events Found",

        "gps_title" to "GPS Live Tracking & Trip Logs",
        "gps_sub" to "Real-time Location, Geofencing & Route History",

        "family_sharing_title" to "Family Sharing & Drivers",
        "family_sharing_sub" to "Multi-User Vehicle Sharing, Driver Profiles & Transfers",

        "section_management" to "MANAGEMENT & SERVICES",
        "section_preferences" to "APP PREFERENCES & TOOLS",
        "cloud_account_offline" to "Local Account (Offline)",
        "cloud_sync_desc" to "Sign in to backup & sync data across devices",
        "btn_sign_in" to "Sign In",
        "btn_profile" to "Profile",
        "user_profile_title" to "User Profile",
        "cloud_signin_title" to "Cloud Account Sign In",

        "got_it" to "Got It",
        "dont_show_again" to "Don't Show Again",
        "reset_feature_guides" to "Reset Feature Guides",
        "reset_feature_guides_desc" to "Re-enable first-time introduction popups for all app features.",
        "guides_reset_toast" to "Feature introduction guides reset successfully!",
        "guide_main_benefits" to "Key Benefits & Capabilities",
        "guide_language_selector" to "Guide Language",

        "guide_dashboard_title" to "Dashboard Overview",
        "guide_dashboard_desc" to "Your central command center for fleet status, expense summaries, and recent activity.",
        "guide_dashboard_benefits" to "• View fleet health score & active vehicles\n• Monitor monthly fuel & total expenses\n• Access trip cost estimator & recent timeline",

        "guide_garage_title" to "My Vehicles (Garage)",
        "guide_garage_desc" to "Manage your vehicle profiles, specifications, odometer readings, and health status.",
        "guide_garage_benefits" to "• Track vehicle specs & license plates\n• Update mileage and odometer readings\n• Generate & share PDF vehicle reports",

        "guide_fuel_title" to "Fuel Tracker",
        "guide_fuel_desc" to "Log gas refuels, calculate real fuel efficiency, and monitor gas station expenses.",
        "guide_fuel_benefits" to "• Track fuel consumption (km/L)\n• Monitor cost per kilometer\n• Analyze monthly gas station expenditure",

        "guide_services_title" to "Maintenance History",
        "guide_services_desc" to "Record oil changes, tire rotations, brake repairs, and upcoming service schedules.",
        "guide_services_benefits" to "• AI smart maintenance recommendations\n• Keep detailed workshop & service logs\n• Track parts replacement history",

        "guide_expenses_title" to "Expense Manager",
        "guide_expenses_desc" to "Track non-fuel vehicle expenses like parking, highway tolls, taxes, and repairs.",
        "guide_expenses_benefits" to "• Categorize parking, tolls, taxes & repairs\n• Expense breakdown per vehicle\n• Visual spending category progress charts",

        "guide_documents_title" to "Vehicle Documents",
        "guide_documents_desc" to "Store registration certificates, PUC licenses, driver's licenses, and permits securely.",
        "guide_documents_benefits" to "• Save issue & expiry dates for documents\n• Expiry warning badges and alerts\n• Keep digital document access on the go",

        "guide_insurance_title" to "Insurance Policies",
        "guide_insurance_desc" to "Track active policy numbers, coverage details, agent hotlines, and renewal dates.",
        "guide_insurance_benefits" to "• Automatic policy expiration warnings\n• One-tap renewal & expense logging\n• Direct agent hotline calling",

        "guide_reminders_title" to "Service Reminders",
        "guide_reminders_desc" to "Set custom due dates for oil changes, tire inspection, battery checks, and renewals.",
        "guide_reminders_benefits" to "• Never miss critical maintenance tasks\n• Integrated with Android system notifications\n• Quick mark completed status",

        "guide_notifications_title" to "Notification Engine",
        "guide_notifications_desc" to "Automated background alerts delivered via Android WorkManager for pending tasks.",
        "guide_notifications_benefits" to "• System alerts for expiring insurance & docs\n• Customizable notification categories\n• Background check even when app is closed",

        "guide_gps_tracking_title" to "GPS Live Tracking",
        "guide_gps_tracking_desc" to "Simulate live vehicle location tracking, geofence alerts, and trip route logs.",
        "guide_gps_tracking_benefits" to "• View live map location & speed\n• Geofence boundary breach alerts\n• Historical trip route analysis",

        "guide_family_sharing_title" to "Family Sharing & Drivers",
        "guide_family_sharing_desc" to "Share vehicle access with family members, manage driver profiles, and assign permissions.",
        "guide_family_sharing_benefits" to "• Multi-user vehicle sharing\n• Driver profiles & contact details\n• Seamless ownership & key transfers",

        "guide_settings_title" to "Settings & Preferences",
        "guide_settings_desc" to "Customize regional units, currency symbols, theme modes, and cloud database sync.",
        "guide_settings_benefits" to "• Multi-currency ($ € £ ₹ ¥) & language options\n• Light & Dark theme preferences\n• JSON data backup & restore",

        "open_battery_settings" to "Open Battery Settings",
        "configure_battery" to "Configure Battery",
        "enable_background_alerts" to "Enable Background Alerts",
        "geofencing_enabled" to "Geofencing Enabled",
        "status_label" to "Status",
        "fine_location" to "Fine Location",
        "background_gps" to "Background GPS",
        "exact_alarms" to "Exact Alarms",
        "unrestricted_battery" to "Unrestricted Battery",
        "granted" to "Granted",
        "grant_location" to "Grant Location",
        "allow_background" to "Allow Background",
        "enable_alarms" to "Enable Alarms",
        "geofence_all_met" to "All background location & alarm rules met",
        "geofence_bg_desc" to "Enable background tracking to receive Safe Zone entry and exit alerts even when the app is closed.",
        "step_location" to "Step 1: Location Permission",
        "step_bg_location" to "Step 2: Background Location",
        "step_exact_alarms" to "Step 3: Exact Alarms",
        "step_battery" to "Step 4: Battery & Background Performance",
        "battery_unrestricted_toast" to "Battery settings: Set Battery to 'Unrestricted' for reliable alerts.",
        "battery_manual_toast" to "Please go to Device Settings > Apps > DriveCare > Battery > Select 'Unrestricted'",
        "done" to "Done",
        "skip_close" to "Skip for now",
        "status_enabled" to "Status: Enabled",
        "status_partially_enabled" to "Status: Partially Enabled",
        "status_disabled" to "Status: Disabled",
        "safe_zone_title" to "Enable Background Alerts (Optional)",
        "safe_zone_sub" to "Safe Zone & Boundary Tracking Setup",
        "alerts_delayed_note" to "Alerts may be delayed due to battery restrictions.",
        "fine_location_desc" to "Needed to pinpoint current coordinates and position Safe Zones accurately on the map.",
        "bg_location_desc" to "Needed to trigger Safe Zone entry and exit notifications automatically even when DriveCare is closed.",
        "exact_alarms_desc" to "Needed to schedule precise geofence boundary checks and maintenance reminders without system delays.",
        "battery_guide_desc" to "Allowing background activity ensures instant Safe Zone entry and exit alerts without delays from Android battery saver.",
        "battery_optimization_disabled" to "Battery Restrictions Removed ✓",

        "app_theme" to "App Theme",
        "back" to "Back",
        "system_default" to "System Default",
        "light_mode" to "Light Mode",
        "dark_mode" to "Dark Mode",
        "gps_hardware_trackers" to "GPS Tracker Devices",
        "gps_live_tracking" to "Live GPS Tracking",
        "location_history_logs" to "Location History Logs",
        "registered_trackers_count" to "%d registered tracker(s) • %d online",
        "api_guide" to "API Guide",
        "no_trackers_registered" to "No GPS Trackers Registered",
        "no_trackers_desc" to "Add physical hardware GPS trackers using IMEI and SIM number.",
        "register_first_tracker" to "Register First Tracker",
        "delete_tracker_title" to "Delete GPS Tracker",
        "delete_tracker_confirm" to "Are you sure you want to delete tracker '%s'?",
        "hardware_integration_guide" to "Hardware Integration API Guide",
        "imei_number" to "IMEI Number",
        "sim_phone_number" to "SIM Phone Number",
        "assigned_vehicle" to "Assigned Vehicle",
        "last_contact" to "Last Contact",
        "never" to "Never",
        "live_map" to "Live Map",
        "history" to "History",
        "register_new_tracker" to "Register New GPS Tracker",
        "edit_tracker" to "Edit GPS Tracker",
        "tracker_name_req" to "Tracker Name *",
        "hardware_imei_req" to "Hardware IMEI Number *",
        "sim_card_phone" to "SIM Card Phone Number",
        "assign_to_vehicle" to "Assign to Vehicle:",
        "notes_install_info" to "Notes & Installation Info",
        "save_tracker" to "Save Tracker",
        "status_online" to "Online",
        "status_offline" to "Offline",
        "live_gps_fleet_tracking" to "Live GPS Fleet Tracking",
        "hardware_imei_label" to "Hardware IMEI:",
        "speed_label" to "Speed:",
        "heading_label" to "Heading:",
        "latitude_label" to "Latitude:",
        "longitude_label" to "Longitude:",
        "geofence_safe_zones" to "Geofence Safe Zones",
        "add_safe_zone" to "Add Safe Zone",
        "delete_safe_zone" to "Delete Safe Zone",
        "no_safe_zones_created" to "No safe zones created",
        "safe_zone_name" to "Safe Zone Name",
        "radius_meters" to "Radius (meters)",
        "location_coordinates" to "Location Coordinates",
        "speed_alert_threshold" to "Speed Alert Threshold (km/h)",
        "simulate_gps_movement" to "Simulate GPS Movement",
        "trigger_geofence_breach" to "Trigger Geofence Breach Event",
        "gps_tracker_management" to "GPS Tracker Management",
        "simulation_mode_active" to "Simulation Mode Active",
        "gps_location_history" to "GPS Location History",
        "filter_by_date_range" to "Filter by Date Range",
        "total_points_logged" to "Total Points Logged",
        "total_distance_tracked" to "Total Distance Tracked",
        "max_speed_reached" to "Max Speed Reached",
        "export_history_gpx_kml" to "Export History (GPX/KML)",
        "clear_history_logs" to "Clear History Logs",
        "no_location_history_found" to "No location history points found for this vehicle.",
        "timestamp" to "Timestamp",
        "lat_lng" to "Latitude / Longitude",
        "speed" to "Speed",
        "event_type" to "Event Type",
        "notif_service_due_title" to "Service Due: %s",
        "notif_service_due_msg" to "%s is due on %s. Keep your vehicle maintained!",
        "notif_doc_expired_title" to "Document Expired: %s",
        "notif_doc_expired_msg" to "%s for %s expired on %s. Please renew immediately.",
        "notif_doc_expiring_title" to "Document Expiring Soon: %s",
        "notif_doc_expiring_msg" to "%s for %s expires on %s.",
        "notif_ins_expired_title" to "Insurance Expired: %s",
        "notif_ins_expired_msg" to "Insurance Policy #%s (%s) expired on %s!",
        "notif_ins_expiring_title" to "Insurance Renewal Alert",
        "notif_ins_expiring_msg" to "%s policy #%s expires in less than 30 days (%s).",
        "notif_tracker_offline_title" to "GPS Tracker Offline Alert",
        "notif_tracker_offline_msg" to "Tracker '%s' (IMEI: %s) has been silent for over 24 hours. Check hardware power or SIM card signal.",
        "notif_geofence_entered" to "Entered Safe Zone: %s",
        "notif_geofence_exited" to "Exited Safe Zone: %s",

        "management_services" to "Management & Services",
        "insurance_renewals_menu" to "Insurance & Renewals",
        "insurance_policies_sub" to "Insurance policies, claims & expiry alerts",
        "expense_manager_menu" to "Expense Manager",
        "expense_manager_sub" to "Track vehicle operational expenses & breakdown",
        "vehicle_timeline_menu" to "Vehicle Timeline",
        "vehicle_timeline_sub" to "Chronological activity log of fuel, maintenance & events",
        "gps_hardware_menu" to "GPS Tracker Devices",
        "gps_hardware_sub" to "Manage Teltonika, Concox, SinoTrack, Coban hardware & IMEI",
        "gps_live_tracking_menu" to "Live Worldwide Tracking",
        "gps_live_tracking_sub" to "Real-time hardware positioning, speed & coordinates",
        "gps_location_history_menu" to "Location History",
        "gps_location_history_sub" to "Historical route points & position logs",
        "gps_tracking_menu" to "Safe Zones & Geofencing",
        "gps_tracking_sub" to "Geofence perimeter alerts & automated notifications",
        "family_sharing_menu" to "Family & Multi-User Sharing",
        "family_sharing_sub" to "Grant vehicle access to family members or drivers",
        "documents_sub" to "Store & track vehicle documents, IDs & permits",
        "emergency_sub" to "Mechanics, roadside assistance & emergency contacts",
        "achievements_sub" to "Safe driving badges & eco-friendly maintenance streaks",
        "app_preferences_tools" to "App Preferences & Tools",
        "settings_sub" to "Theme, notifications, regional units & security",
        "current_language" to "Current Language",
        "backup_restore_sub" to "Export JSON backup or restore records",
        "about_drivecare_sub" to "Version 2.0.0 Global Edition",
        "brand_showcase_title" to "Brand & Logo Showcase",
        "brand_showcase_sub" to "Official DriveCare logo, color palette & Play Store assets"
    )

    private val urduMap = mapOf(
        "app_name" to "ڈرائیو کیئر",
        "tab_dashboard" to "ڈیش بورڈ",
        "tab_garage" to "گاڑیاں",
        "tab_fuel" to "ایندھن",
        "tab_services" to "سروسز",
        "tab_service" to "سروسز",
        "tab_more" to "مزید",
        "tab_documents" to "دستاویزات",
        "tab_emergency" to "ہنگامی مدد",
        "tab_achievements" to "کامیابیاں",
        "tab_settings" to "سیٹنگز",
        "tab_reminders" to "یاد دہانی",
        "backup_restore" to "بیک اپ اور ری سٹور",
        
        "total_vehicles" to "کل گاڑیاں",
        "upcoming_services" to "آنے والی سروسز",
        "active_insurance" to "فعال انشورنس",
        "monthly_fuel_cost" to "ماہانہ ایندھن کا خرچ",
        "total_fuel_entries" to "کل ایندھن کے ریکارڈ",
        "vehicle_health_score" to "گاڑی کی صحت کا اسکور",
        
        "health_excellent" to "بہترین",
        "health_good" to "اچھا",
        "health_fair" to "مناسب",
        "health_poor" to "کمزور",
        
        "add_vehicle" to "گاڑی شامل کریں",
        "edit_vehicle" to "گاڑی تبدیل کریں",
        "delete_vehicle" to "گاڑی ختم کریں",
        "no_vehicles_title" to "ابھی تک کوئی گاڑی شامل نہیں کی گئی",
        "no_vehicles_desc" to "اپنی پہلی گاڑی شامل کرنے کے لیے بٹن پر کلک کریں۔",
        "vehicle_name" to "گاڑی کا نام",
        "brand" to "کمپنی / برانڈ",
        "model" to "ماڈل",
        "year" to "سال",
        "plate_no" to "نمبر پلیٹ",
        "fuel_type" to "ایندھن کی قسم",
        "odometer" to "میٹر ریڈنگ (کلو میٹر)",
        "type" to "گاڑی کی قسم",
        "fuel" to "ایندھن",
        "plate" to "نمبر پلیٹ",

        "vtype_car" to "کار",
        "vtype_motorcycle" to "موٹر سائیکل",
        "vtype_scooter" to "اسکوٹر",
        "vtype_bus" to "بس",
        "vtype_van" to "وین",
        "vtype_pickup_truck" to "پک اپ ٹرک",
        "vtype_suv" to "ایس یو وی",
        "vtype_jeep" to "جیپ",
        "vtype_taxi" to "ٹیکسی",
        "vtype_truck" to "ٹرک",
        "vtype_tractor" to "ٹریکٹر",
        "vtype_trailer" to "ٹریلر",
        "vtype_minibus" to "منی بس",
        "vtype_rv_camper" to "آر وی / کیمپر",
        "vtype_electric_car" to "الیکٹرک کار",
        "vtype_hybrid_car" to "ہائبرڈ کار",
        "vtype_bicycle" to "سائیکل",
        "vtype_fleet" to "گاڑیوں کا بیڑا",
        "vtype_other" to "دیگر (کسٹم)",
        
        "log_fuel" to "ایندھن درج کریں",
        "select_vehicle" to "گاڑی منتخب کریں",
        "all_vehicles" to "تمام گاڑیاں",
        "total_spent" to "کل خرچ",
        "total_quantity" to "کل مقدار (لیٹر)",
        "litres" to "لیٹر",
        "cost" to "قیمت ($)",
        "gas_station" to "پیٹرول پمپ",
        "no_fuel_entries" to "ایندھن کا کوئی ریکارڈ نہیں مل سکا۔",
        
        "add_service_log" to "سروس درج کریں",
        "service_title" to "تفصیل (مثلاً آئل چینج)",
        "workshop" to "ورکشاپ",
        "no_service_logs" to "کوئی سروس ریکارڈ نہیں",
        "no_service_desc" to "آئل چینج اور ٹیوننگ کا ہسٹری ٹریک کریں۔",
        
        "add_reminder" to "یاد دہانی لگائیں",
        "reminder_title" to "عنوان",
        "due_date" to "تاریخ",
        "no_reminders" to "کوئی یاد دہانی نہیں",
        "no_reminders_desc" to "انشورنس اور سروس کے لیے یاد دہانی سیٹ کریں۔",
        
        "save" to "محفوظ کریں",
        "cancel" to "منسوخ کریں",
        "delete" to "ختم کریں",
        "confirm_delete_title" to "گاڑی ختم کریں",
        "confirm_delete_msg" to "کیا آپ یقینی طور پر اس گاڑی کو ڈلیٹ کرنا چاہتے ہیں؟",
        "change_language" to "زبان تبدیل کریں",
        
        "overview_title" to "ڈرائیو کیئر جائزہ",
        "pending_tasks" to "بقیہ کام",
        "fuel_spent" to "ایندھن کا خرچ",
        "service_spent" to "سروس کا خرچ",
        "fleet_summary" to "گاڑیوں کی حالت کا جائزہ",
        "vehicles_count" to "گاڑیاں",
        "no_vehicles_registered" to "گیراج میں کوئی گاڑی درج نہیں ہے۔",
        "trip_calculator" to "سفر کے اخراجات کا اندازہ",
        "health_score" to "گاڑی کی صحت",
        "calculate_trip" to "حساب لگائیں",
        "distance_km" to "سفر کا فاصلہ (کلو میٹر)",
        "fuel_price" to "ایندھن کی قیمت فی لیٹر ($)",
        "avg_mileage" to "اوسط مائلیج (km/L)",
        "estimated_cost" to "متوقع خرچ",
        "passengers" to "مسافروں کی تعداد",
        "cost_per_person" to "فی کس خرچ",
        "calculate" to "حساب لگائیں",
        
        "advisor_title" to "سمارٹ سروس مشیر",
        "advisor_subtitle" to "گاڑی کی کلومیٹر اور ہسٹری کے مطابق خودکار تجاویز۔",
        "oil_change_due" to "انجن آئل تبدیل کرنے کی ضرورت ہے",
        "brake_inspection_due" to "بریک پیڈز کی چیکنگ ضروری ہے",
        "air_filter_due" to "ایئر فلٹر تبدیل کریں",
        "coolant_check_due" to "کولنٹ لیول چیک کریں",
        "battery_check_due" to "بیٹری کی حالت چیک کریں",
        "tire_rotation_due" to "ٹائر روٹیشن اور بیلنسنگ",
        
        "vehicle_profile" to "گاڑی کا پروفائل",
        "export_pdf" to "پی ڈی ایف رپورٹ بنائیں",
        "share_pdf" to "رپورٹ شیئر کریں",
        "pdf_generated" to "پی ڈی ایف رپورٹ کامیابی سے بن گئی",
        
        "add_document" to "دستاویز شامل کریں",
        "doc_type" to "دستاویز کی قسم",
        "issue_date" to "اجراء کی تاریخ",
        "expiry_date" to "میعاد ختم ہونے کی تاریخ",
        "no_documents" to "کوئی دستاویزات محفوظ نہیں ہیں",

        "emergency_title" to "روڈ سائیڈ ایمرجنسی مدد",
        "one_tap_call" to "ایک ٹیپ سے کال کریں",
        "mechanic" to "مکینک",
        "family" to "اہل خانہ",
        "insurance_hotline" to "انشورنس ہیلپ لائن",
        "towing_service" to "ٹو ٹرک سروس",
        "add_contact" to "ایمرجنسی نمبر شامل کریں",
        "no_contacts" to "کوئی ہنگامی نمبر موجود نہیں",
        
        "achievements_title" to "کامیابیاں اور ایوارڈز",
        "settings_title" to "ایپ سیٹنگز",
        "theme_mode" to "ڈارک موڈ",
        "language" to "زبان کا انتخاب",
        "backup_data" to "بیک اپ لیں (JSON)",
        "restore_data" to "ریسٹور کریں",
        "notifications" to "نوٹیفیکیشنز",
        "about_drivecare" to "ڈرائیو کیئر ورژن 2.0.0",

        "analytics_cost_breakdown" to "اخراجات کا تجزیہ",
        "monthly_fuel_expenditure" to "ماہانہ ایندھن کا خرچ ($)",
        "expense_category_breakdown" to "اخراجات کی اقسام",
        "total_expense_logged" to "کل اخراجات",
        "recent_timeline_activity" to "حالیہ سرگرمیاں",
        "view_all" to "تمام دیکھیں",
        "no_recent_activity" to "ابھی کوئی حالیہ سرگرمی نہیں ہے۔",
        "vehicles_active_fleet" to "فعال گاڑیاں",
        "tasks_pending" to "بقیہ کام",
        "all_tasks_up_to_date" to "تمام کام مکمل ہیں",
        "fleet_health_label" to "گاڑیوں کی صحت",
        "fuel_efficiency" to "ایندھن کی اوسط",
        "cost_label" to "خرچ",

        "insurance_policies_title" to "انشورنس اور پالیسیاں",
        "insurance_policies_sub" to "پالیسی کی تفصیلات اور یاد دہانی",
        "status_active" to "فعال",
        "status_expiring_soon" to "جلد ختم ہونے والی",
        "status_expired" to "ختم شدہ",
        "filter_all" to "تمام",
        "filter_expiring" to "میعاد ختم",
        "no_policies_found" to "کوئی انشورنس پالیسی نہیں ملی",
        "no_policies_desc" to "انشورنس پالیسی شامل کرنے کے لیے نیچے بٹن دبائیں۔",
        "policy_no_prefix" to "پالیسی نمبر",
        "vehicle_linked" to "منسلک گاڑی",
        "coverage_type" to "کوریج کی قسم",
        "premium" to "پریمیم",
        "valid_period" to "میعاد",
        "auto_renew_on" to "آٹو رینیو فعال",
        "btn_renew" to "تجدید کریں",
        "btn_agent" to "ایجنٹ",
        "add_policy_title" to "انشورنس پالیسی شامل کریں",
        "edit_policy_title" to "پالیسی تبدیل کریں",
        "provider_name" to "انشورنس کمپنی کا نام",
        "policy_number" to "پالیسی نمبر",
        "start_date" to "شروعات کی تاریخ",
        "agent_phone" to "ایجنٹ فون نمبر",
        "notes_info" to "نوٹس / اضافی معلومات",
        "enable_autorenew" to "آٹو رینیو کی سچیچ آن کریں",
        "save_policy" to "پالیسی محفوظ کریں",
        "update_policy" to "پالیسی اپ ڈیٹ کریں",
        "renew_policy_title" to "پالیسی کی تجدید کریں #",
        "new_start_date" to "نئی شروعاتی تاریخ",
        "new_expiry_date" to "نئی آخری تاریخ",
        "renewal_premium" to "تجدید کی رقم",
        "confirm_renewal" to "تجدید کی تصدیق اور خرچ درج کریں",
        "delete_policy_title" to "انشورنس پالیسی ختم کریں",

        "expense_manager_title" to "اخراجات کے مینیجر",
        "expense_manager_sub" to "پارکنگ، ٹول، انشورنس اور ٹیکس کا ٹریکر",
        "total_vehicle_expenses" to "گاڑی کے کل اخراجات",
        "category_breakdown" to "اقسام کے اخراجات",
        "expense_history" to "اخراجات کی ہسٹری",
        "no_expenses_found" to "کوئی اخراجات درج نہیں ہیں",
        "no_expenses_desc" to "پارکنگ یا دیگر اخراجات درج کرنے کے لیے بٹن دبائیں۔",
        "add_expense" to "خرچ درج کریں",
        "log_new_expense" to "نیا خرچ درج کریں",
        "expense_title" to "خرچ کی تفصیل",
        "category" to "قسم",
        "amount" to "رقم",
        "date" to "تاریخ",

        "timeline_title" to "گاڑی کی ہسٹری ٹائم لائن",
        "timeline_sub" to "ایندھن، سروس اور اخراجات کا مکمل ریکارڈ",
        "no_timeline_found" to "کوئی ریکارڈ موجود نہیں",

        "gps_title" to "جی پی ایس لائیو ٹریکنگ",
        "gps_sub" to "لائیو لوکیشن اور سفر کا ہسٹری ریکارڈ",

        "family_sharing_title" to "فیملی شیئرنگ اور ڈرائیورز",
        "family_sharing_sub" to "گاڑی کی ملٹی یوزر شیئرنگ",

        "section_management" to "سروسز اور انتظامی امور",
        "section_preferences" to "سیٹنگز اور ٹولز",
        "cloud_account_offline" to "لوکل اکاؤنٹ (آف لائن)",
        "cloud_sync_desc" to "ڈیٹا بیک اپ کے لیے سائن ان کریں",
        "btn_sign_in" to "سائن ان کریں",
        "btn_profile" to "پروفائل",
        "user_profile_title" to "صارف کا پروفائل",
        "cloud_signin_title" to "کلاؤڈ سائن ان",

        "got_it" to "سمجھ گیا",
        "dont_show_again" to "دوبارہ نہ دکھائیں",
        "reset_feature_guides" to "فیچر گائیڈز ری سیٹ کریں",
        "reset_feature_guides_desc" to "تمام خصوصیات کے تعارفی پاپ اپس دوبارہ فعال کریں۔",
        "guides_reset_toast" to "فیچر گائیڈز کامیابی کے ساتھ ری سیٹ ہو گئیں!",
        "guide_main_benefits" to "اہم فوائد اور قابلیتیں",
        "guide_language_selector" to "گائیڈ کی زبان",

        "guide_dashboard_title" to "ڈیش بورڈ کا جائزہ",
        "guide_dashboard_desc" to "آپ کی گاڑیوں کی حالت، اخراجات کے خلاصے اور حالیہ سرگرمیوں کا مرکزی مرکز۔",
        "guide_dashboard_benefits" to "• گاڑیوں کا ہیلتھ اسکور اور فعال گاڑیاں دیکھیں\n• ماہانہ ایندھن اور کل اخراجات کی نگرانی کریں\n• ٹرپ لاگت کا تخمینہ اور ہسٹری دیکھیں",

        "guide_garage_title" to "میری گاڑیاں (گیراج)",
        "guide_garage_desc" to "اپنی گاڑیوں کے پروفائلز، کیلو میٹر ریڈنگ اور ہیلتھ اسٹیٹس کا انتظام کریں۔",
        "guide_garage_benefits" to "• نمبر پلیٹ اور گاڑی کی تفصیلات محفوظ کریں\n• مائلج اور اوڈومیٹر ریڈنگ اپ ڈیٹ کریں\n• پی ڈی ایف رپورٹ بنائیں اور شیئر کریں",

        "guide_fuel_title" to "ایندھن کا ٹریکر",
        "guide_fuel_desc" to "پیٹرول بھروانے کا ریکارڈ رکھیں، مائلج کا حساب لگائیں اور اخراجات دیکھیں۔",
        "guide_fuel_benefits" to "• ایندھن کی اوسط (km/L) ٹریک کریں\n• فی کلو میٹر خرچ کا حساب لگائیں\n• ماہانہ ایندھن کے اخراجات کا تجزیہ کریں",

        "guide_services_title" to "سروس اور مرمت کی ہسٹری",
        "guide_services_desc" to "آئل چینج، بریک سروس اور آئندہ کی مرمت کا مکمل ریکارڈ رکھیں۔",
        "guide_services_benefits" to "• سمارٹ سروس مشیر کی خودکار تجاویز\n• ورکشاپ اور سروس کی تفصیلات محفوظ کریں\n• پارٹس کی تبدیلی کی تاریخ کا ریکارڈ",

        "guide_expenses_title" to "اخراجات کا مینیجر",
        "guide_expenses_desc" to "پارکنگ، ٹول ٹیکس، انشورنس اور دیگر غیر ایندھن اخراجات کا ریکارڈ رکھیں۔",
        "guide_expenses_benefits" to "• پارکنگ، ٹول اور ٹیکسز کی درجہ بندی\n• ہر گاڑی کا الگ خرچ کا جائزہ\n• اخراجات کا گرافکل چارٹ",

        "guide_documents_title" to "گاڑی کی دستاویزات",
        "guide_documents_desc" to "رجسٹریشن، ڈرائیونگ لائسنس اور پرمٹ محفوظ طریقے سے اسٹور کریں۔",
        "guide_documents_benefits" to "• دستاویزات کی آخری تاریخیں محفوظ کریں\n• میعاد ختم ہونے پر الرٹس حاصل کریں\n• ڈیجیٹل کاپیاں ہر وقت دستیاب رکھیں",

        "guide_insurance_title" to "انشورنس پالیسیاں",
        "guide_insurance_desc" to "پالیسی نمبرز، کوریج کی تفصیلات، ایجنٹ نمبر اور رینیول کی تاریخیں دیکھیں۔",
        "guide_insurance_benefits" to "• پالیسی ختم ہونے کے خودکار الرٹس\n• ایک کلک پر تجدید اور خرچ کا اندراج\n• ایجنٹ کو براہ راست کال کرنے کی سہولت",

        "guide_reminders_title" to "سروس کی یاد دہانیاں",
        "guide_reminders_desc" to "آئل چینج، ٹائر چیکنگ اور بیٹری سروس کی تاریخوں کے لیے یاد دہانی سیٹ کریں۔",
        "guide_reminders_benefits" to "• اہم مرمتی کام کبھی مس نہ ہوں\n• اینڈرائڈ سسٹم نوٹیفیکیشنز کے ساتھ منسلک\n• ایک ٹیپ پر کام مکمل مارک کریں",

        "guide_notifications_title" to "نوٹیفیکیشن انجن",
        "guide_notifications_desc" to "بقیہ کاموں اور میعاد ختم ہونے پر بیک گراؤنڈ میں خودکار الرٹس حاصل کریں۔",
        "guide_notifications_benefits" to "• انشورنس اور دستاویزات کے بروقت الرٹس\n• نوٹیفیکیشن کی ترجیحات تبدیل کریں\n• ایپ بند ہونے پر بھی الرٹس حاصل کریں",

        "guide_gps_tracking_title" to "جی پی ایس لائیو ٹریکنگ",
        "guide_gps_tracking_desc" to "گاڑی کی لائیو لوکیشن، جیوفینس الرٹس اور روٹ ہسٹری دیکھیں۔",
        "guide_gps_tracking_benefits" to "• میپ پر لائیو لوکیشن اور اسپیڈ دیکھیں\n• جیوفینس کی حد عبور ہونے پر الرٹس\n• پرانے سفر کا مکمل تجزیہ",

        "guide_family_sharing_title" to "فیملی شیئرنگ اور ڈرائیورز",
        "guide_family_sharing_desc" to "اہل خانہ کے ساتھ گاڑیوں کی رسائی شیئر کریں اور ڈرائیورز کے پروفائلز مینیج کریں۔",
        "guide_family_sharing_benefits" to "• ملٹی یوزر گاڑی کی شیئرنگ\n• ڈرائیور پروفائلز اور فون نمبرز\n• گاڑی کی منتقلی اور چابی ہینڈ اوور",

        "guide_settings_title" to "سیٹنگز اور ترجیحات",
        "guide_settings_desc" to "زبان، کرنسی سمبل، ڈارک موڈ اور ڈیٹا بیک اپ کی سیٹنگز تبدیل کریں۔",
        "guide_settings_benefits" to "• ملٹی کرنسی ($ € £ ₹ ¥) اور زبانیں\n• لائٹ اور ڈارک تھیم\n• JSON ڈیٹا بیک اپ اور ریسٹور",

        "open_battery_settings" to "بیٹری سیٹنگز کھولیں",
        "configure_battery" to "بیٹری کنفیگر کریں",
        "enable_background_alerts" to "بیک گراؤنڈ الرٹس فعال کریں",
        "geofencing_enabled" to "جیو فینسنگ فعال ہے",
        "status_label" to "حیثیت",
        "fine_location" to "مقام کی اجازت",
        "background_gps" to "بیک گراؤنڈ GPS",
        "exact_alarms" to "درست الارم",
        "unrestricted_battery" to "غیر محدود بیٹری",
        "granted" to "منظور شدہ",
        "grant_location" to "مقام کی اجازت دیں",
        "allow_background" to "بیک گراؤنڈ کی اجازت دیں",
        "enable_alarms" to "الارم فعال کریں",
        "geofence_all_met" to "تمام پس منظر لوکیشن اور الارم قواعد مکمل ہیں",
        "geofence_bg_desc" to "سیف زون کے الرٹس حاصل کرنے کے لیے پس منظر میں ٹریکنگ فعال کریں۔",
        "step_location" to "مرحلہ 1: لوکیشن کی اجازت",
        "step_bg_location" to "مرحلہ 2: بیک گراؤنڈ لوکیشن",
        "step_exact_alarms" to "مرحلہ 3: درست الارم",
        "step_battery" to "مرحلہ 4: بیٹری اور بیک گراؤنڈ پرفارمنس",
        "battery_unrestricted_toast" to "بیٹری سیٹنگز: الرٹس کے لیے 'Unrestricted' سیٹ کریں۔",
        "battery_manual_toast" to "سیٹنگز > ایپس > ڈرائیو کیئر > بیٹری > 'Unrestricted' منتخب کریں",
        "done" to "مکمل",
        "skip_close" to "ابھی کے لیے چھوڑ دیں",
        "status_enabled" to "حالت: فعال",
        "status_partially_enabled" to "حالت: جزوی فعال",
        "status_disabled" to "حالت: غیر فعال",
        "safe_zone_title" to "بیک گراؤنڈ الرٹس فعال کریں (اختیاری)",
        "safe_zone_sub" to "سیف زون اور حد بندی کا سیٹ اپ",
        "alerts_delayed_note" to "بیٹری کے حدود کی وجہ سے الرٹس میں تاخیر ہو سکتی ہے۔",
        "fine_location_desc" to "نقشے پر درست مقام اور سیف زون متعین کرنے کے لیے درکار ہے۔",
        "bg_location_desc" to "ڈرائیو کیئر بند ہونے پر بھی سیف زون کے الرٹس بھیجنے کے لیے درکار ہے۔",
        "exact_alarms_desc" to "باقاعدہ جیو فینس چیکس اور دیکھ بھال کی یاد دہانیوں کے لیے درکار ہے۔",
        "battery_guide_desc" to "سیف زون کے بر وقت الرٹس موصول کرنے کے لیے بیک گراؤنڈ ایکٹیویٹی کو بلا تاخیر فعال رکھیں۔",
        "battery_optimization_disabled" to "بیٹری کی پابندیاں ختم کر دی گئی ہیں ✓",

        "app_theme" to "ایپ کی تھیم",
        "back" to "واپس",
        "system_default" to "سسٹم ڈیفالٹ",
        "light_mode" to "لائٹ موڈ",
        "dark_mode" to "ڈارک موڈ",
        "gps_hardware_trackers" to "GPS ٹریکر آلات",
        "gps_live_tracking" to "لائیو GPS ٹریکنگ",
        "location_history_logs" to "لوکیشن ہسٹری لاگز",
        "registered_trackers_count" to "%d درج شدہ ٹریکر • %d آن لائن",
        "api_guide" to "API گائیڈ",
        "no_trackers_registered" to "کوئی GPS ٹریکر درج نہیں ہے",
        "no_trackers_desc" to "IMEI اور SIM نمبر کے ذریعے حقیقی GPS ٹریکر آلات شامل کریں۔",
        "register_first_tracker" to "پہلا ٹریکر درج کریں",
        "delete_tracker_title" to "GPS ٹریکر حذف کریں",
        "delete_tracker_confirm" to "کیا آپ واقعتاً ٹریکر '%s' حذف کرنا چاہتے ہیں؟",
        "hardware_integration_guide" to "ہارڈویئر انٹیگریشن API گائیڈ",
        "imei_number" to "IMEI نمبر",
        "sim_phone_number" to "SIM فون نمبر",
        "assigned_vehicle" to "مخصوص گاڑی",
        "last_contact" to "آخری رابطہ",
        "never" to "کبھی نہیں",
        "live_map" to "لائیو نقشہ",
        "history" to "ہسٹری",
        "register_new_tracker" to "نیا GPS ٹریکر رجسٹر کریں",
        "edit_tracker" to "GPS ٹریکر ترمیم کریں",
        "tracker_name_req" to "ٹریکر کا نام *",
        "hardware_imei_req" to "ہارڈویئر IMEI نمبر *",
        "sim_card_phone" to "سم کارڈ فون نمبر",
        "assign_to_vehicle" to "گاڑی منتخب کریں:",
        "notes_install_info" to "نوٹس اور تنصیب کی معلومات",
        "save_tracker" to "ٹریکر محفوظ کریں",
        "status_online" to "آن لائن",
        "status_offline" to "آف لائن",
        "live_gps_fleet_tracking" to "لائیو GPS فلیٹ ٹریکنگ",
        "hardware_imei_label" to "ہارڈویئر IMEI:",
        "speed_label" to "رفتار:",
        "heading_label" to "سمت:",
        "latitude_label" to "عرض بلد:",
        "longitude_label" to "طول بلد:",
        "geofence_safe_zones" to "جیوفینس سیف زونز",
        "add_safe_zone" to "سیف زون شامل کریں",
        "delete_safe_zone" to "سیف زون حذف کریں",
        "no_safe_zones_created" to "کوئی سیف زون نہیں بنایا گیا",
        "safe_zone_name" to "سیف زون کا نام",
        "radius_meters" to "نصف قطر (میٹر)",
        "location_coordinates" to "لوکیشن کوآرڈینیٹس",
        "speed_alert_threshold" to "اسپیڈ الرٹ کی حد (کلو میٹر/گھنٹہ)",
        "simulate_gps_movement" to "GPS موومنٹ سمیلیٹ کریں",
        "trigger_geofence_breach" to "جیوفینس کی خلاف ورزی کا واقعہ محرک کریں",
        "gps_tracker_management" to "GPS ٹریکر مینجمنٹ",
        "simulation_mode_active" to "سمیلیشن موڈ فعال",
        "gps_location_history" to "GPS لوکیشن ہسٹری",
        "filter_by_date_range" to "تاریخ کے لحاظ سے فلٹر کریں",
        "total_points_logged" to "کل پوائنٹس لاگ ہوئے",
        "total_distance_tracked" to "کل فاصلہ ٹریک ہوا",
        "max_speed_reached" to "زیادہ سے زیادہ رفتار",
        "export_history_gpx_kml" to "ہسٹری برآمد کریں (GPX/KML)",
        "clear_history_logs" to "ہسٹری لاگز صاف کریں",
        "no_location_history_found" to "اس گاڑی کی کوئی لوکیشن ہسٹری نہیں ملی۔",
        "timestamp" to "ٹائم اسٹیمپ",
        "lat_lng" to "عرض بلد / طول بلد",
        "speed" to "رفتار",
        "event_type" to "واقعہ کی قسم",
        "notif_service_due_title" to "سروس کا وقت: %s",
        "notif_service_due_msg" to "%s کی سروس %s کو ہونا واجب ہے۔ گاڑی کی دیکھ بھال جاری رکھیں!",
        "notif_doc_expired_title" to "دستاویز کی مدت ختم: %s",
        "notif_doc_expired_msg" to "%s کی دستاویز %s کیلئے %s کو ختم ہو چکی ہے۔ براہ کرم فوری تجدید کریں!",
        "notif_doc_expiring_title" to "دستاویز جلد ختم ہونے والی ہے: %s",
        "notif_doc_expiring_msg" to "%s کی دستاویز %s کیلئے %s کو ختم ہو جائے گی۔",
        "notif_ins_expired_title" to "انشورنس کی مدت ختم: %s",
        "notif_ins_expired_msg" to "انشورنس پالیسی #%s (%s) %s کو ختم ہو چکی ہے!",
        "notif_ins_expiring_title" to "انشورنس تجدید الرٹ",
        "notif_ins_expiring_msg" to "%s پالیسی #%s 30 دن سے کم میں ختم ہو جائے گی (%s)۔",
        "notif_tracker_offline_title" to "GPS ٹریکر آف لائن الرٹ",
        "notif_tracker_offline_msg" to "ٹریکر '%s' (IMEI: %s) 24 گھنٹے سے خاموش ہے۔ ہارڈویئر پاور یا سم سگنل چیک کریں۔",
        "notif_geofence_entered" to "سیف زون میں داخلہ: %s",
        "notif_geofence_exited" to "سیف زون سے خروج: %s",

        "management_services" to "انتظام اور خدمات",
        "insurance_renewals_menu" to "انشورنس اور تجدید",
        "insurance_policies_sub" to "انشورنس پالیسیاں، کلیمز اور میعاد کی تنبیہات",
        "expense_manager_menu" to "اخراجات کا منیجر",
        "expense_manager_sub" to "گاڑی کے تمام اخراجات کا حساب رکھیں",
        "vehicle_timeline_menu" to "گاڑی کی ٹائم لائن",
        "vehicle_timeline_sub" to "ایندھن، سروسز اور واقعات کا ہسٹری لاگ",
        "gps_hardware_menu" to "جی پی ایس ٹریکر ڈیوائسز",
        "gps_hardware_sub" to "ہارڈ ویئر ڈیوائسز اور آئی ایم ای آئی کا انتظام کریں",
        "gps_live_tracking_menu" to "لائیو ورلڈ وائڈ ٹریکنگ",
        "gps_live_tracking_sub" to "براہ راست پوزیشن، رفتار اور لوکیشن",
        "gps_location_history_menu" to "لوکیشن ہسٹری",
        "gps_location_history_sub" to "پرانے روٹس اور سفر کی ہسٹری",
        "gps_tracking_menu" to "سیف زونز اور جیو فینسنگ",
        "gps_tracking_sub" to "جیو فینس کی حد اور خودکار الرٹس",
        "family_sharing_menu" to "فیملی اور ملٹی یوزر شیئرنگ",
        "family_sharing_sub" to "اہل خانہ یا ڈرائیورز کو گاڑی کی رسائی دیں",
        "documents_sub" to "گاڑی کی دستاویزات، شناختی کارڈ اور پرمٹ محفوظ رکھیں",
        "emergency_sub" to "مکینک، سڑک کے کنارے امداد اور ہنگامی رابطے",
        "achievements_sub" to "محفوظ ڈرائیونگ بیجز اور بہترین سروس کی کامیابی",
        "app_preferences_tools" to "ایپ کی ترجیحات اور ٹولز",
        "settings_sub" to "تھیم، نوٹیفکیشنز، اکائیاں اور سیکیورٹی",
        "current_language" to "موجودہ زبان",
        "backup_restore_sub" to "JSON بیک اپ حاصل کریں یا ریسٹور کریں",
        "about_drivecare_sub" to "ورژن 2.0.0 گلوبل ایڈیشن",
        "brand_showcase_title" to "برانڈ اور لوگو شوکیس",
        "brand_showcase_sub" to "ڈرائیو کیئر کا آفیشل لوگو اور پلے اسٹور اثاثے"
    )

    private val arabicMap = mapOf(
        "app_name" to "درايف كير",
        "tab_dashboard" to "لوحة التحكم",
        "tab_garage" to "المركبات",
        "tab_fuel" to "الوقود",
        "tab_services" to "الصيانة",
        "tab_service" to "الصيانة",
        "tab_more" to "المزيد",
        "tab_documents" to "الوثائق",
        "tab_emergency" to "الطوارئ",
        "tab_achievements" to "الإنجازات",
        "tab_settings" to "الإعدادات",
        "tab_reminders" to "التذكيرات",
        "backup_restore" to "النسخ الاحتياطي والاستعادة",
        
        "total_vehicles" to "إجمالي المركبات",
        "upcoming_services" to "الصيانة القادمة",
        "active_insurance" to "التأمين النشط",
        "monthly_fuel_cost" to "تكلفة الوقود الشهرية",
        "total_fuel_entries" to "سجلات الوقود",
        "vehicle_health_score" to "مؤشر صحة المركبة",
        
        "health_excellent" to "ممتاز",
        "health_good" to "جيد",
        "health_fair" to "مقبول",
        "health_poor" to "ضعيف",
        
        "add_vehicle" to "إضافة مركبة",
        "edit_vehicle" to "تعديل المركبة",
        "delete_vehicle" to "حذف المركبة",
        "no_vehicles_title" to "لم يتم إضافة مركبات بعد",
        "no_vehicles_desc" to "اضغط على الزر أدناه لإضافة أول مركبة.",
        "vehicle_name" to "اسم المركبة",
        "brand" to "الماركة",
        "model" to "الموديل",
        "year" to "السنة",
        "plate_no" to "رقم لوحة السيارة",
        "fuel_type" to "نوع الوقود",
        "odometer" to "قراءة العداد (كم)",

        "vtype_car" to "سيارة",
        "vtype_motorcycle" to "دراجة نارية",
        "vtype_scooter" to "سكوتر",
        "vtype_bus" to "حافلة (باص)",
        "vtype_van" to "شاحنة صغيرة (فان)",
        "vtype_pickup_truck" to "شاحنة بيك آب",
        "vtype_suv" to "سيارة دفع رباعي (SUV)",
        "vtype_jeep" to "جيب",
        "vtype_taxi" to "سيارة أجرة (تاكسي)",
        "vtype_truck" to "شاحنة",
        "vtype_tractor" to "جرار زراعي",
        "vtype_trailer" to "مقطورة",
        "vtype_minibus" to "حافلة صغيرة (ميني باص)",
        "vtype_rv_camper" to "كرفان / عربة تخييم",
        "vtype_electric_car" to "سيارة كهربائية",
        "vtype_hybrid_car" to "سيارة هجينة",
        "vtype_bicycle" to "دراجة هوائية",
        "vtype_fleet" to "أسطول مركبات",
        "vtype_other" to "أخرى (مخصص)",

        "status_active" to "نشط",
        "status_expiring_soon" to "ينتهي قريباً",
        "status_expired" to "منتهي",
        "filter_all" to "الكل",
        "insurance_policies_title" to "التأمين والوثائق",
        "insurance_policies_sub" to "تفاصيل البوليصة والتذكيرات",
        "expense_manager_title" to "إدارة المصاريف",
        "expense_manager_sub" to "متابعة الرسوم والمواقف والتأمين",
        "timeline_title" to "السجل الزمني للمركبة",
        "gps_title" to "تتبع GPS والرحلات",
        "family_sharing_title" to "المشاركة العائلية",
        "section_management" to "الخدمات والإدارة",
        "section_preferences" to "تفضيلات التطبيق والأدوات",
        "cloud_account_offline" to "حساب محلي (غير متصل)",
        "cloud_sync_desc" to "تسجيل الدخول للنسخ الاحتياطي",
        "btn_sign_in" to "تسجيل الدخول",
        "btn_profile" to "الملف الشخصي",
        "user_profile_title" to "الملف الشخصي",
        "cloud_signin_title" to "تسجيل الدخول السحابي",
        "analytics_cost_breakdown" to "تحليل المصاريف",
        "monthly_fuel_expenditure" to "إنفاق الوقود الشهري ($)",
        "expense_category_breakdown" to "توزيع المصاريف حسب الفئة",
        "total_expense_logged" to "إجمالي المصاريف المسجلة",
        "recent_timeline_activity" to "الأنشطة الأخيرة",
        "view_all" to "عرض الكل",
        "no_recent_activity" to "لا توجد أنشطة حديثة مسجلة.",
        "vehicles_active_fleet" to "مركبات نشطة في الأسطول",
        "tasks_pending" to "مهام معلقة",
        "all_tasks_up_to_date" to "جميع المهام مكتملة",

        "got_it" to "فهمت",
        "dont_show_again" to "عدم إظهار المرة القادمة",
        "reset_feature_guides" to "إعادة ضبط أدلة الميزات",
        "reset_feature_guides_desc" to "إعادة تمكين الإرشادات التعريفية لجميع ميزات التطبيق.",
        "guides_reset_toast" to "تم إعادة ضبط أدلة الميزات بنجاح!",
        "guide_main_benefits" to "المزايا والقدرات الرئيسية",
        "guide_language_selector" to "لغة الدليل",

        "guide_dashboard_title" to "نظرة عامة على لوحة التحكم",
        "guide_dashboard_desc" to "مركز التحكم الرئيسي لحالة الأسطول، وملخص المصاريف، والأنشطة الأخيرة.",
        "guide_dashboard_benefits" to "• عرض مؤشر صحة الأسطول والمركبات النشطة\n• متابعة إنفاق الوقود الشهري والمصاريف الكلية\n• حاسبة تكاليف الرحلات والسجل الزمني",

        "guide_garage_title" to "مركباتي (المرأب)",
        "guide_garage_desc" to "إدارة ملفات المركبات، والمواصفات، وقراءات العداد، وحالة الصحة.",
        "guide_garage_benefits" to "• تتبع مواصفات المركبة وأرقام اللوحات\n• تحديث قراءات العداد والمسافات\n• إنشاء ومشاركة تقارير PDF",

        "guide_fuel_title" to "متبع الوقود",
        "guide_fuel_desc" to "تسجيل تعبئة الوقود، وحساب كفاءة الاستهلاك الحقيقية، ومتابعة مصاريف المحطات.",
        "guide_fuel_benefits" to "• تتبع معدل استهلاك الوقود (كم/لتر)\n• متابعة التكلفة لكل كيلومتر\n• تحليل مصاريف الوقود الشهرية",

        "guide_services_title" to "سجل الصيانة",
        "guide_services_desc" to "تسجيل تغيير الزيت، وتدوير الإطارات، وإصلاح الفرامل، ومواعيد الصيانة القادمة.",
        "guide_services_benefits" to "• توصيات الصيانة الذكية من الذكاء الاصطناعي\n• الاحتفاظ بسجلات الورشة والصيانة المفصلة\n• تتبع تاريخ استبدال قطع الغيار",

        "guide_expenses_title" to "مدير المصاريف",
        "guide_expenses_desc" to "تتبع مصاريف المركبة غير الوقود مثل المواقف، والرسوم، والضرائب، والإصلاحات.",
        "guide_expenses_benefits" to "• تصنيف المواقف والرسوم والضرائب للإصلاحات\n• تفصيل المصاريف لكل مركبة\n• رسوم بيانية توضيحية لفئات الإنفاق",

        "guide_documents_title" to "وثائق المركبة",
        "guide_documents_desc" to "حفظ رخص السير، وشهادات الفحص، ورخص القيادة، والتصاريح بآمان.",
        "guide_documents_benefits" to "• حفظ تواريخ الإصدار والانتهاء للوثائق\n• شارات وتنبيهات لانتهاء الصلاحية\n• الوصول الرقمي للوثائق في أي وقت",

        "guide_insurance_title" to "وثائق التأمين",
        "guide_insurance_desc" to "تتبع أرقام الوثائق النشطة، وتفاصيل التغطية، وهواتف الوكلاء، وتواريخ التجديد.",
        "guide_insurance_benefits" to "• تنبيهات تلقائية لانتهاء وثائق التأمين\n• التجديد وتسجيل المصاريف بنقرة واحدة\n• الاتصال المباشر بخط طوارئ الوكيل",

        "guide_reminders_title" to "تذكيرات الصيانة",
        "guide_reminders_desc" to "تعيين مواعيد مخصصة لتغيير الزيت، وفحص الإطارات، والبطارية، والتجديدات.",
        "guide_reminders_benefits" to "• عدم تفويت مهام الصيانة الهامة مطلقاً\n• متكامل مع إشعارات نظام أندرويد\n• تعليم المهام كمكتملة بضغطة واحدة",

        "guide_notifications_title" to "محرك الإشعارات",
        "guide_notifications_desc" to "تنبيهات خلفية تلقائية عبر Android WorkManager للمهام المعلقة.",
        "guide_notifications_benefits" to "• تنبيهات النظام للتأمين والوثائق المنتهية\n• فئات إشعارات قابلة للتخصيص\n• الفحص في الخلفية حتى عند إغلاق التطبيق",

        "guide_gps_tracking_title" to "التتبع المباشر بـ GPS",
        "guide_gps_tracking_desc" to "محاكاة التتبع المباشر لموقع المركبة، وتنبيهات السياج الجغرافي، وسجلات الرحلات.",
        "guide_gps_tracking_benefits" to "• عرض الموقع المباشر والسرعة على الخريطة\n• تنبيهات اختراق حدود السياج الجغرافي\n• تحليل مسار الرحلات السابقة",

        "guide_family_sharing_title" to "المشاركة العائلية والسائقون",
        "guide_family_sharing_desc" to "مشاركة الوصول للمركبة مع أفراد العائلة، وإدارة ملفات السائقين، وتحديد الصلاحيات.",
        "guide_family_sharing_benefits" to "• مشاركة المركبة بين عدة مستخدمين\n• ملفات السائقين ومعلومات الاتصال\n• نقل الملكية والمفاتيح بسهولة",

        "guide_settings_title" to "الإعدادات والتفضيلات",
        "guide_settings_desc" to "تخصيص الوحدات والإقليمية، ورمز العملة، والوضع الليلي، والمزامنة السحابية.",
        "guide_settings_benefits" to "• خيارات العملات ($ € £ ₹ ¥) واللغات المتعددة\n• التبديل بين الوضع المظلم والفاتح\n• نسخ واعادة استعادة البيانات بصيغة JSON",

        "open_battery_settings" to "فتح إعدادات البطارية",
        "configure_battery" to "تكوين البطارية",
        "enable_background_alerts" to "تمكين تنبيهات الخلفية",
        "geofencing_enabled" to "السياج الجغرافي مفعل",
        "status_label" to "الحالة",
        "fine_location" to "الموقع الدقيق",
        "background_gps" to "GPS في الخلفية",
        "exact_alarms" to "منبهات دقيقة",
        "unrestricted_battery" to "بطارية غير مقيدة",
        "granted" to "ممنوح",
        "grant_location" to "منح الموقع",
        "allow_background" to "السماح في الخلفية",
        "enable_alarms" to "تمكين المنبهات",
        "geofence_all_met" to "تم استيفاء جميع قواعد الموقع والإنذارات في الخلفية",
        "geofence_bg_desc" to "قم بتمكين التتبع في الخلفية لتلقي تنبيهات المنطقة الآمنة.",
        "step_location" to "الخطوة 1: إذن الموقع",
        "step_bg_location" to "الخطوة 2: الموقع في الخلفية",
        "step_exact_alarms" to "الخطوة 3: المنبهات الدقيقة",
        "step_battery" to "الخطوة 4: إرشادات تحسين البطارية",
        "battery_unrestricted_toast" to "إعدادات البطارية: اضبط البطارية على 'غير مقيدة' للتنبيهات.",
        "battery_manual_toast" to "الانتقال إلى الإعدادات > التطبيقات > درايف كير > البطارية > اختر 'غير مقيدة'",
        "done" to "تم",
        "skip_close" to "التخطي الآن",
        "status_enabled" to "الحالة: مُمكّن",
        "status_partially_enabled" to "الحالة: مُمكّن جزئياً",
        "status_disabled" to "الحالة: معطل",
        "safe_zone_title" to "تمكين تنبيهات الخلفية (اختياري)",
        "safe_zone_sub" to "إعداد المنطقة الآمنة وتتبع الحدود",
        "alerts_delayed_note" to "قد تتأخر التنبيهات بسبب قيود البطارية.",
        "fine_location_desc" to "مطلوب لتحديد الإحداثيات الحالية والمناطق الآمنة بدقة.",
        "bg_location_desc" to "مطلوب لتشغيل إشعارات المنطقة الآمنة تلقائياً عند إغلاق التطبيق.",
        "exact_alarms_desc" to "مطلوب لجدولة فحص حدود السياج الجغرافي والتذكيرات بدقة.",
        "battery_guide_desc" to "يمنع وضع إيقاف النظام من وضع مستمعي الخلفية في حالة السكون.",
        "battery_optimization_disabled" to "تم تعطيل تحسين البطارية ✓",

        "app_theme" to "سمة التطبيق",
        "back" to "رجوع",
        "system_default" to "افتراضي النظام",
        "light_mode" to "الوضع الفاتح",
        "dark_mode" to "الوضع المظلم",
        "gps_hardware_trackers" to "أجهزة تتبع GPS",
        "gps_live_tracking" to "التتبع المباشر بـ GPS",
        "location_history_logs" to "سجل المواقع والرحلات",
        "registered_trackers_count" to "%d جهاز مسجل • %d متصل",
        "api_guide" to "دليل API",
        "no_trackers_registered" to "لا توجد أجهزة تتبع مسجلة",
        "no_trackers_desc" to "أضف أجهزة تتبع GPS حقيقية باستخدام رقم IMEI ورقم شريحة SIM.",
        "register_first_tracker" to "تسجيل أول جهاز تتبع",
        "delete_tracker_title" to "حذف جهاز التتبع",
        "delete_tracker_confirm" to "هل أنت ألكيد من حذف جهاز التتبع '%s'؟",
        "hardware_integration_guide" to "دليل تكامل هاردوير API",
        "imei_number" to "رقم IMEI",
        "sim_phone_number" to "رقم شريحة SIM",
        "assigned_vehicle" to "المركبة المعينة",
        "last_contact" to "آخر اتصال",
        "never" to "أبداً",
        "live_map" to "الخريطة المباشرة",
        "history" to "السجل",
        "register_new_tracker" to "تسجيل جهاز تتبع جديد",
        "edit_tracker" to "تعديل جهاز التتبع",
        "tracker_name_req" to "اسم الجهاز *",
        "hardware_imei_req" to "رقم IMEI للجهاز *",
        "sim_card_phone" to "رقم هاتف شريحة SIM",
        "assign_to_vehicle" to "تعيين للمركبة:",
        "notes_install_info" to "الملاحظات ومعلومات التثبيت",
        "save_tracker" to "حفظ الجهاز",
        "status_online" to "متصل",
        "status_offline" to "غير متصل",
        "live_gps_fleet_tracking" to "تتبع الأسطول المباشر بـ GPS",
        "hardware_imei_label" to "رقم IMEI:",
        "speed_label" to "السرعة:",
        "heading_label" to "الاتجاه:",
        "latitude_label" to "خط العرض:",
        "longitude_label" to "خط الطول:",
        "geofence_safe_zones" to "مناطق السياج الجغرافي الآمنة",
        "add_safe_zone" to "إضافة منطقة آمنة",
        "delete_safe_zone" to "حذف المنطقة الآمنة",
        "no_safe_zones_created" to "لم يتم إنشاء مناطق آمنة",
        "safe_zone_name" to "اسم المنطقة الآمنة",
        "radius_meters" to "نصف القطر (بالمتر)",
        "location_coordinates" to "إحداثيات الموقع",
        "speed_alert_threshold" to "حد تنبيه السرعة (كم/ساعة)",
        "simulate_gps_movement" to "محاكاة حركة GPS",
        "trigger_geofence_breach" to "تشغيل حدث اختراق السياج الجغرافي",
        "gps_tracker_management" to "إدارة أجهزة تتبع GPS",
        "simulation_mode_active" to "وضع المحاكاة نشط",
        "gps_location_history" to "سجل مواقع GPS",
        "filter_by_date_range" to "تصفية حسب نطاق التاريخ",
        "total_points_logged" to "إجمالي النقاط المسجلة",
        "total_distance_tracked" to "إجمالي المسافة المتتبعة",
        "max_speed_reached" to "أقصى سرعة مسجلة",
        "export_history_gpx_kml" to "تصدير السجل (GPX/KML)",
        "clear_history_logs" to "مسح سجل السجل",
        "no_location_history_found" to "لم يتم العثور على سجل مواقع لهذه المركبة.",
        "timestamp" to "الطابع الزمني",
        "lat_lng" to "خط العرض / الطول",
        "speed" to "السرعة",
        "event_type" to "نوع الحدث",
        "notif_service_due_title" to "موعد الصيانة: %s",
        "notif_service_due_msg" to "موعد %s يستحق في %s. حافظ على صيانة مركبتك!",
        "notif_doc_expired_title" to "انتهت صلاحية الوثيقة: %s",
        "notif_doc_expired_msg" to "انتهت صلاحية %s للمركبة %s في %s. يرجى التجديد فوراً.",
        "notif_doc_expiring_title" to "الوثيقة تنتهي قريباً: %s",
        "notif_doc_expiring_msg" to "تنتهي صلاحية %s للمركبة %s في %s.",
        "notif_ins_expired_title" to "انتهت صلاحية التأمين: %s",
        "notif_ins_expired_msg" to "انتهت صلاحية وثيقة التأمين رقم #%s (%s) في %s!",
        "notif_ins_expiring_title" to "تنبيه تجديد التأمين",
        "notif_ins_expiring_msg" to "تنتهي وثيقة %s رقم #%s خلال أقل من 30 يوماً (%s).",
        "notif_tracker_offline_title" to "تنبيه توقف جهاز GPS",
        "notif_tracker_offline_msg" to "الجهاز '%s' (IMEI: %s) متوقف منذ أكثر من 24 ساعة. تحقق من الطاقة وشريحة SIM.",
        "notif_geofence_entered" to "دخول المنطقة الآمنة: %s",
        "notif_geofence_exited" to "خروج من المنطقة الآمنة: %s",

        "management_services" to "الإدارة والخدمات",
        "insurance_renewals_menu" to "التأمين والتجديدات",
        "insurance_policies_sub" to "بوالص التأمين والمطالبات وتنبيهات الانتهاء",
        "expense_manager_menu" to "إدارة المصاريف",
        "expense_manager_sub" to "تتبع مصاريف التشغيل وتفاصيل التكاليف",
        "vehicle_timeline_menu" to "الجدول الزمني للمركبة",
        "vehicle_timeline_sub" to "سجل حافل بالأنشطة للوقود والصيانة والأحداث",
        "gps_hardware_menu" to "أجهزة تتبع GPS",
        "gps_hardware_sub" to "إدارة أجهزة التتبع والرقم التسلسلي IMEI",
        "gps_live_tracking_menu" to "التتبع المباشر حول العالم",
        "gps_live_tracking_sub" to "التحديد المباشر للموقع والسرعة والإحداثيات",
        "gps_location_history_menu" to "سجل المواقع",
        "gps_location_history_sub" to "نقاط المسار التاريخية وسجلات الموقع",
        "gps_tracking_menu" to "المناطق الآمنة والسياج الجغرافي",
        "gps_tracking_sub" to "تنبيهات حدود السياج الجغرافي والإشعارات الآلية",
        "family_sharing_menu" to "المشاركة العائلية والمتعددة",
        "family_sharing_sub" to "منح صلاحيات الوصول للمركبة لأفراد العائلة أو السائقين",
        "documents_sub" to "حفظ وتتبع مستندات المركبة والتراخيص",
        "emergency_sub" to "الميكانيكيون والمساعدة على الطريق وجدول الطوارئ",
        "achievements_sub" to "شارات القيادة الآمنة وسجلات الصيانة البيئية",
        "app_preferences_tools" to "تفضيلات التطبيق والأدوات",
        "settings_sub" to "المظهر، الإشعارات، الوحدات الإقليمية والأمان",
        "current_language" to "اللغة الحالية",
        "backup_restore_sub" to "تصدير نسخة احتياطية أو استعادة البيانات",
        "about_drivecare_sub" to "الإصدار 2.0.0 النسخة العالمية",
        "brand_showcase_title" to "معرض العلامة التجارية والشعار",
        "brand_showcase_sub" to "الشعار الرسمي وألوان ومتجر بلاي أصول"
    )

    private val hindiMap = mapOf(
        "app_name" to "ड्राइवकेयर",
        "tab_dashboard" to "डैशबोर्ड",
        "tab_garage" to "वाहन",
        "tab_fuel" to "ईंधन",
        "tab_services" to "सर्विस",
        "tab_service" to "सर्विस",
        "tab_more" to "अन्य",
        "tab_documents" to "दस्तावेज़",
        "tab_emergency" to "आपातकालीन सेवा",
        "tab_achievements" to "उपलब्धियां",
        "tab_settings" to "सेटिंग्स",
        "tab_reminders" to "रिमाइंडर",
        "backup_restore" to "बैकअप और रिस्टोर",

        "vtype_car" to "कार",
        "vtype_motorcycle" to "मोटरसाइकिल",
        "vtype_scooter" to "स्कूटर",
        "vtype_bus" to "बस",
        "vtype_van" to "वैन",
        "vtype_pickup_truck" to "पिकअप ट्रक",
        "vtype_suv" to "एसयूवी (SUV)",
        "vtype_jeep" to "जीप",
        "vtype_taxi" to "टैक्सी",
        "vtype_truck" to "ट्रक",
        "vtype_tractor" to "ट्रैक्टर",
        "vtype_trailer" to "ट्रेलर",
        "vtype_minibus" to "मिनीबस",
        "vtype_rv_camper" to "आरवी / कैंपर",
        "vtype_electric_car" to "इलेक्ट्रिक कार",
        "vtype_hybrid_car" to "हाइब्रिड कार",
        "vtype_bicycle" to "साइकिल",
        "vtype_fleet" to "गाड़ियों का बेड़ा",
        "vtype_other" to "अन्य (कस्टम)",
        
        "total_vehicles" to "कुल वाहन",
        "upcoming_services" to "आगामी सर्विस",
        "active_insurance" to "सक्रिय बीमा",
        "monthly_fuel_cost" to "मासिक ईंधन खर्च",
        "total_fuel_entries" to "कुल ईंधन लॉग",
        "vehicle_health_score" to "वाहन स्वास्थ्य स्कोर",

        "status_active" to "सक्रिय",
        "status_expiring_soon" to "शीघ्र समाप्त होने वाला",
        "status_expired" to "समाप्त",
        "filter_all" to "सभी",
        "insurance_policies_title" to "बीमा और नीतियां",
        "insurance_policies_sub" to "नीति विवरण और नवीनीकरण रिमाइंडर",
        "expense_manager_title" to "खर्च प्रबंधक",
        "expense_manager_sub" to "पार्किंग, टोल और बीमा खर्च ट्रैक करें",
        "timeline_title" to "वाहन टाइमलाइन",
        "gps_title" to "जीपीएस ट्रैकिंग",
        "family_sharing_title" to "फैमिली शेयरिंग",
        "section_management" to "प्रबंधन और सेवाएं",
        "section_preferences" to "ऐप प्राथमिकताएं और टूल्स",
        "cloud_account_offline" to "स्थानीय खाता (ऑफ़लाइन)",
        "cloud_sync_desc" to "डेटा बैकअप के लिए साइन इन करें",
        "btn_sign_in" to "साइन इन करें",
        "btn_profile" to "प्रोफ़ाइल",
        "user_profile_title" to "उपयोगकर्ता प्रोफ़ाइल",
        "cloud_signin_title" to "क्लाउड साइन इन",
        "analytics_cost_breakdown" to "लागत विश्लेषण",
        "monthly_fuel_expenditure" to "मासिक ईंधन खर्च ($)",
        "expense_category_breakdown" to "श्रेणी के अनुसार खर्च",
        "total_expense_logged" to "कुल दर्ज खर्च",
        "recent_timeline_activity" to "हाल की गतिविधियां",
        "view_all" to "सभी देखें",
        "no_recent_activity" to "कोई हालिया गतिविधि नहीं है।",
        "vehicles_active_fleet" to "सक्रिय वाहन",
        "tasks_pending" to "लंबित कार्य",
        "all_tasks_up_to_date" to "सभी कार्य पूर्ण हैं",

        "got_it" to "समझ गया",
        "dont_show_again" to "पुनः न दिखाएं",
        "reset_feature_guides" to "फ़ीचर गाइड रीसेट करें",
        "reset_feature_guides_desc" to "सभी ऐप सुविधाओं के लिए परिचयात्मक पॉपअप फिर से सक्षम करें।",
        "guides_reset_toast" to "फ़ीचर गाइड सफलतापूर्वक रीसेट हो गए!",
        "guide_main_benefits" to "मुख्य लाभ एवं क्षमताएं",
        "guide_language_selector" to "गाइड भाषा",

        "guide_dashboard_title" to "डैशबोर्ड अवलोकन",
        "guide_dashboard_desc" to "आपके बेड़े की स्थिति, खर्च सारांश और हालिया गतिविधियों का मुख्य केंद्र।",
        "guide_dashboard_benefits" to "• वाहन स्वास्थ्य स्कोर और सक्रिय वाहन देखें\n• मासिक ईंधन और कुल खर्चों की निगरानी करें\n• यात्रा लागत कैलकुलेटर और हालिया टाइमलाइन",

        "guide_garage_title" to "मेरे वाहन (गैरेज)",
        "guide_garage_desc" to "अपने वाहनों के प्रोफाइल, स्पेसिफिकेशन, ओडोमीटर रीडिंग और स्वास्थ्य स्थिति प्रबंधित करें।",
        "guide_garage_benefits" to "• वाहन विवरण और नंबर प्लेट ट्रैक करें\n• माइलेज और ओडोमीटर रीडिंग अपडेट करें\n• पीडीएफ रिपोर्ट बनाएं और साझा करें",

        "guide_fuel_title" to "ईंधन ट्रैकर",
        "guide_fuel_desc" to "ईंधन भरवाने का रिकॉर्ड रखें, वास्तविक माइलेज का हिसाब लगाएं और खर्च देखें।",
        "guide_fuel_benefits" to "• ईंधन खपत (km/L) ट्रैक करें\n• प्रति किलोमीटर लागत की निगरानी करें\n• मासिक ईंधन व्यय का विश्लेषण करें",

        "guide_services_title" to "सर्विस इतिहास",
        "guide_services_desc" to "तेल परिवर्तन, टायर रोटेशन, ब्रेक मरम्मत और आगामी सर्विस शेड्यूल रिकॉर्ड करें।",
        "guide_services_benefits" to "• एआई स्मार्ट रखरखाव सिफारिशें\n• विस्तृत कार्यशाला और सेवा लॉग रखें\n• पुर्जों के प्रतिस्थापन इतिहास को ट्रैक करें",

        "guide_expenses_title" to "खर्च प्रबंधक",
        "guide_expenses_desc" to "पार्किंग, टोल, टैक्स और मरम्मत जैसे गैर-ईंधन खर्चों को ट्रैक करें।",
        "guide_expenses_benefits" to "• पार्किंग, टोल, टैक्स और मरम्मत को वर्गीकृत करें\n• प्रति वाहन खर्च का विवरण\n• दृश्य व्यय श्रेणी प्रगति चार्ट",

        "guide_documents_title" to "वाहन दस्तावेज़",
        "guide_documents_desc" to "पंजीकरण प्रमाण पत्र, ड्राइविंग लाइसेंस और परमिट सुरक्षित रूप से संग्रहीत करें।",
        "guide_documents_benefits" to "• दस्तावेजों के जारी होने और समाप्ति तिथि सहेजें\n• समाप्ति चेतावनी बैज और अलर्ट\n• यात्रा के दौरान डिजिटल दस्तावेज़ों तक पहुँच",

        "guide_insurance_title" to "बीमा नीतियां",
        "guide_insurance_desc" to "सक्रिय नीति संख्या, कवरेज विवरण, एजेंट हेल्पलाइन और नवीनीकरण तिथियां ट्रैक करें।",
        "guide_insurance_benefits" to "• स्वचालित बीमा समाप्ति चेतावनियां\n• एक-टैप नवीनीकरण और खर्च लॉगिंग\n• एजेंट हेल्पलाइन पर सीधे कॉल करें",

        "guide_reminders_title" to "सर्विस रिमाइंडर",
        "guide_reminders_desc" to "तेल परिवर्तन, टायर निरीक्षण, बैटरी जांच और नवीनीकरण के लिए रिमाइंडर्स सेट करें।",
        "guide_reminders_benefits" to "• कभी भी महत्वपूर्ण रखरखाव कार्य न भूलें\n• एंड्रॉइड सिस्टम नोटिफिकेशन के साथ एकीकृत\n• त्वरित कार्य पूर्ण स्थिति दर्ज करें",

        "guide_notifications_title" to "नोटिफिकेशन इंजन",
        "guide_notifications_desc" to "लंबित कार्यों के लिए एंड्रॉइड वर्कमैनेजर के माध्यम से स्वचालित पृष्ठभूमि अलर्ट।",
        "guide_notifications_benefits" to "• समाप्त हो रहे बीमा और दस्तावेजों के लिए सिस्टम अलर्ट\n• अनुकूलन योग्य अधिसूचना श्रेणियां\n• ऐप बंद होने पर भी बैकग्राउंड चेक",

        "guide_gps_tracking_title" to "जीपीएस लाइव ट्रैकिंग",
        "guide_gps_tracking_desc" to "लाइव वाहन स्थान ट्रैकिंग, जियोफेंस अलर्ट और यात्रा मार्ग लॉग का अनुकरण करें।",
        "guide_gps_tracking_benefits" to "• मानचित्र पर लाइव स्थान और गति देखें\n• जियोफेंस सीमा उल्लंघन अलर्ट\n• ऐतिहासिक यात्रा मार्ग विश्लेषण",

        "guide_family_sharing_title" to "फैमिली शेयरिंग और ड्राइवर्स",
        "guide_family_sharing_desc" to "परिवार के सदस्यों के साथ वाहन की पहुंच साझा करें, ड्राइवर प्रोफाइल प्रबंधित करें।",
        "guide_family_sharing_benefits" to "• बहु-उपयोगकर्ता वाहन साझाकरण\n• ड्राइवर प्रोफाइल और संपर्क विवरण\n• निर्बाध स्वामित्व और कुंजी स्थानांतरण",

        "guide_settings_title" to "सेटिंग्स और प्राथमिकताएं",
        "guide_settings_desc" to "क्षेत्रीय इकाइयों, मुद्रा प्रतीकों, थीम मोड और क्लाउड डेटाबेस सिंक को कस्टमाइज़ करें।",
        "guide_settings_benefits" to "• बहु-मुद्रा ($ € £ ₹ ¥) और भाषा विकल्प\n• लाइट और डार्क थीम प्राथमिकताएं\n• JSON डेटा बैकअप और रिस्टोर",

        "open_battery_settings" to "बैटरी सेटिंग्स खोलें",
        "configure_battery" to "बैटरी कॉन्फ़िगर करें",
        "enable_background_alerts" to "बैकग्राउंड अलर्ट सक्षम करें",
        "geofencing_enabled" to "जियोफेंसिंग सक्षम",
        "status_label" to "स्थिति",
        "fine_location" to "स्थान अनुमति",
        "background_gps" to "बैकग्राउंड GPS",
        "exact_alarms" to "सटीक अलार्म",
        "unrestricted_battery" to "अनप्रतिबंधित बैटरी",
        "granted" to "स्वीकृत",
        "grant_location" to "स्थान अनुमति दें",
        "allow_background" to "बैकग्राउंड अनुमति दें",
        "enable_alarms" to "अलार्म सक्षम करें",
        "geofence_all_met" to "सभी बैकग्राउंड स्थान और अलार्म नियम पूरे हुए",
        "geofence_bg_desc" to "सुरक्षित क्षेत्र अलर्ट प्राप्त करने के लिए बैकग्राउंड ट्रैकिंग सक्षम करें।",
        "step_location" to "चरण 1: स्थान अनुमति",
        "step_bg_location" to "चरण 2: बैकग्राउंड स्थान",
        "step_exact_alarms" to "चरण 3: सटीक अलार्म",
        "step_battery" to "चरण 4: बैटरी अनुकूलन मार्गदर्शन",
        "battery_unrestricted_toast" to "बैटरी सेटिंग्स: अलर्ट के लिए बैटरी को 'अनप्रतिबंधित' पर सेट करें।",
        "battery_manual_toast" to "सेटिंग्स > ऐप > ड्राइवकेयर > बैटरी > 'अनप्रतिबंधित' चुनें",
        "done" to "हो गया",
        "skip_close" to "अभी के लिए छोड़ें",
        "status_enabled" to "स्थिति: सक्षम",
        "status_partially_enabled" to "स्थिति: आंशिक रूप से सक्षम",
        "status_disabled" to "स्थिति: अक्षम",
        "safe_zone_title" to "बैकग्राउंड अलर्ट सक्षम करें (वैकल्पिक)",
        "safe_zone_sub" to "सेफ ज़ोन और सीमा ट्रैकिंग सेटअप",
        "alerts_delayed_note" to "बैटरी प्रतिबंधों के कारण अलर्ट में देरी हो सकती है।",
        "fine_location_desc" to "मानचित्र पर सटीक स्थान और सेफ ज़ोन निर्धारित करने के लिए आवश्यक।",
        "bg_location_desc" to "ऐप बंद होने पर भी स्वचालित रूप से सेफ ज़ोन सूचनाएं ट्रिगर करने के लिए आवश्यक।",
        "exact_alarms_desc" to "सटीक जियोफेंस सीमा जांच और रखरखाव अनुस्मारक शेड्यूल करने के लिए आवश्यक।",
        "battery_guide_desc" to "अलर्ट विश्वसनीयता के लिए सिस्टम को बैकग्राउंड प्रक्रियाओं को सोने से रोकता है।",
        "battery_optimization_disabled" to "बैटरी अनुकूलन अक्षम है ✓",

        "app_theme" to "ऐप थीम",
        "back" to "पीछे जाएँ",
        "system_default" to "सिस्टम डिफ़ॉल्ट",
        "light_mode" to "लाइट मोड",
        "dark_mode" to "डार्क मोड",
        "gps_hardware_trackers" to "जीपीएस ट्रैकर उपकरण",
        "gps_live_tracking" to "लाइव जीपीएस ट्रैकिंग",
        "location_history_logs" to "स्थान इतिहास लॉग",
        "registered_trackers_count" to "%d पंजीकृत ट्रैकर • %d ऑनलाइन",
        "api_guide" to "एपीआई गाइड",
        "no_trackers_registered" to "कोई जीपीएस ट्रैकर पंजीकृत नहीं है",
        "no_trackers_desc" to "IMEI और सिम नंबर का उपयोग करके भौतिक जीपीएस ट्रैकर उपकरण जोड़ें।",
        "register_first_tracker" to "पहला ट्रैकर पंजीकृत करें",
        "delete_tracker_title" to "जीपीएस ट्रैकर हटाएं",
        "delete_tracker_confirm" to "क्या आप निश्चित रूप से ट्रैकर '%s' को हटाना चाहते हैं?",
        "hardware_integration_guide" to "हार्डवेयर एकीकरण एपीआई गाइड",
        "imei_number" to "IMEI नंबर",
        "sim_phone_number" to "सिम फोन नंबर",
        "assigned_vehicle" to "आवंटित वाहन",
        "last_contact" to "अंतिम संपर्क",
        "never" to "कभी नहीं",
        "live_map" to "लाइव मानचित्र",
        "history" to "इतिहास",
        "register_new_tracker" to "नया जीपीएस ट्रैकर पंजीकृत करें",
        "edit_tracker" to "जीपीएस ट्रैकर संपादित करें",
        "tracker_name_req" to "ट्रैकर नाम *",
        "hardware_imei_req" to "हार्डवेयर IMEI नंबर *",
        "sim_card_phone" to "सिम कार्ड फोन नंबर",
        "assign_to_vehicle" to "वाहन आवंटित करें:",
        "notes_install_info" to "नोट्स और इंस्टॉलेशन जानकारी",
        "save_tracker" to "ट्रैकर सहेजें",
        "status_online" to "ऑनलाइन",
        "status_offline" to "ऑफ़लाइन",
        "live_gps_fleet_tracking" to "लाइव जीपीएस बेड़ा ट्रैकिंग",
        "hardware_imei_label" to "हार्डवेयर IMEI:",
        "speed_label" to "गति:",
        "heading_label" to "दिशा:",
        "latitude_label" to "अक्षांश:",
        "longitude_label" to "देशांतर:",
        "geofence_safe_zones" to "जियोफेंस सुरक्षित क्षेत्र",
        "add_safe_zone" to "सुरक्षित क्षेत्र जोड़ें",
        "delete_safe_zone" to "सुरक्षित क्षेत्र हटाएं",
        "no_safe_zones_created" to "कोई सुरक्षित क्षेत्र नहीं बनाया गया",
        "safe_zone_name" to "सुरक्षित क्षेत्र का नाम",
        "radius_meters" to "त्रिज्या (मीटर)",
        "location_coordinates" to "स्थान निर्देशांक",
        "speed_alert_threshold" to "गति चेतावनी सीमा (किमी/घंटा)",
        "simulate_gps_movement" to "जीपीएस आंदोलन का अनुकरण करें",
        "trigger_geofence_breach" to "जियोफेंस उल्लंघन घटना ट्रिगर करें",
        "gps_tracker_management" to "जीपीएस ट्रैकर प्रबंधन",
        "simulation_mode_active" to "सिमुलेशन मोड सक्रिय",
        "gps_location_history" to "जीपीएस स्थान इतिहास",
        "filter_by_date_range" to "तिथि सीमा के अनुसार फ़िल्टर करें",
        "total_points_logged" to "कुल बिंदु लॉग किए गए",
        "total_distance_tracked" to "कुल दूरी ट्रैक की गई",
        "max_speed_reached" to "अधिकतम गति",
        "export_history_gpx_kml" to "इतिहास निर्यात करें (GPX/KML)",
        "clear_history_logs" to "इतिहास लॉग साफ़ करें",
        "no_location_history_found" to "इस वाहन के लिए कोई स्थान इतिहास नहीं मिला।",
        "timestamp" to "समय मोहर",
        "lat_lng" to "अक्षांश / देशांतर",
        "speed" to "गति",
        "event_type" to "घटना का प्रकार",
        "notif_service_due_title" to "सर्विस देय: %s",
        "notif_service_due_msg" to "%s की सर्विस %s को देय है। अपने वाहन की देखभाल बनाए रखें!",
        "notif_doc_expired_title" to "दस्तावेज़ समाप्त: %s",
        "notif_doc_expired_msg" to "%s के लिए %s की अवधि %s को समाप्त हो गई है। कृपया तुरंत नवीनीकृत करें।",
        "notif_doc_expiring_title" to "दस्तावेज़ शीघ्र समाप्त हो रहा है: %s",
        "notif_doc_expiring_msg" to "%s के लिए %s की अवधि %s को समाप्त हो जाएगी।",
        "notif_ins_expired_title" to "बीमा समाप्त: %s",
        "notif_ins_expired_msg" to "बीमा पॉलिसी #%s (%s) की अवधि %s को समाप्त हो गई है!",
        "notif_ins_expiring_title" to "बीमा नवीनीकरण चेतावनी",
        "notif_ins_expiring_msg" to "%s पॉलिसी #%s 30 दिनों से कम समय में समाप्त हो जाएगी (%s)।",
        "notif_tracker_offline_title" to "जीपीएस ट्रैकर ऑफ़लाइन चेतावनी",
        "notif_tracker_offline_msg" to "ट्रैकर '%s' (IMEI: %s) 24 घंटे से अधिक समय से शांत है। शक्ति या सिम सिग्नल जांचें।",
        "notif_geofence_entered" to "सुरक्षित क्षेत्र में प्रवेश: %s",
        "notif_geofence_exited" to "सुरक्षित क्षेत्र से बाहर: %s",

        "management_services" to "प्रबंधन और सेवाएं",
        "insurance_renewals_menu" to "बीमा और नवीनीकरण",
        "insurance_policies_sub" to "बीमा पॉलिसियां, दावे और समाप्ति अलर्ट",
        "expense_manager_menu" to "व्यय प्रबंधक",
        "expense_manager_sub" to "वाहन के परिचालन व्यय और विवरण को ट्रैक करें",
        "vehicle_timeline_menu" to "वाहन समय-सीमा",
        "vehicle_timeline_sub" to "ईंधन, रखरखाव और घटनाओं का कालानुक्रमिक लॉग",
        "gps_hardware_menu" to "जीपीएस ट्रैकर उपकरण",
        "gps_hardware_sub" to "हार्डवेयर डिवाइस और IMEI प्रबंधित करें",
        "gps_live_tracking_menu" to "लाइव वर्ल्डवाइड ट्रैकिंग",
        "gps_live_tracking_sub" to "वास्तविक समय की स्थिति, गति और निर्देशांक",
        "gps_location_history_menu" to "स्थान इतिहास",
        "gps_location_history_sub" to "ऐतिहासिक मार्ग बिंदु और स्थिति लॉग",
        "gps_tracking_menu" to "सुरक्षित क्षेत्र और जियोफेंसिंग",
        "gps_tracking_sub" to "जियोफेंस परिधि अलर्ट और स्वचालित सूचनाएं",
        "family_sharing_menu" to "परिवार और मल्टी-यूज़र शेयरिंग",
        "family_sharing_sub" to "परिवार के सदस्यों या ड्राइवरों को वाहन पहुंच प्रदान करें",
        "documents_sub" to "वाहन के दस्तावेज़, आईडी और परमिट स्टोर और ट्रैक करें",
        "emergency_sub" to "मैकेनिक, सड़क किनारे सहायता और आपातकालीन संपर्क",
        "achievements_sub" to "सुरक्षित ड्राइविंग बैज और पर्यावरण-अनुकूल रखरखाव",
        "app_preferences_tools" to "ऐप प्राथमिकताएं और उपकरण",
        "settings_sub" to "थीम, सूचनाएं, क्षेत्रीय इकाइयां और सुरक्षा",
        "current_language" to "वर्तमान भाषा",
        "backup_restore_sub" to "JSON बैकअप निर्यात करें या रिकॉर्ड पुनर्स्थापित करें",
        "about_drivecare_sub" to "संस्करण 2.0.0 ग्लोबल संस्करण",
        "brand_showcase_title" to "ब्रांड और लोगो शोकेस",
        "brand_showcase_sub" to "आधिकारिक ड्राइवकेयर लोगो और संपत्तियां"
    )

    private val chineseMap = mapOf(
        "app_name" to "DriveCare 驭管家",
        "tab_dashboard" to "仪表盘",
        "tab_garage" to "我的车辆",
        "tab_fuel" to "油耗",
        "tab_services" to "保养",
        "tab_service" to "保养",
        "tab_more" to "更多",
        "tab_documents" to "车辆证件",
        "tab_emergency" to "紧急救援",
        "tab_achievements" to "里程成就",
        "tab_settings" to "设置",
        "tab_reminders" to "提醒事项",
        "backup_restore" to "备份与恢复",

        "vtype_car" to "轿车",
        "vtype_motorcycle" to "摩托车",
        "vtype_scooter" to "踏板车",
        "vtype_bus" to "公交车 / 大巴",
        "vtype_van" to "面包车",
        "vtype_pickup_truck" to "皮卡",
        "vtype_suv" to "SUV 越野车",
        "vtype_jeep" to "吉普车",
        "vtype_taxi" to "出租车",
        "vtype_truck" to "卡车 / 货车",
        "vtype_tractor" to "拖拉机",
        "vtype_trailer" to "挂车 / 拖车",
        "vtype_minibus" to "中巴 / 小巴",
        "vtype_rv_camper" to "房车",
        "vtype_electric_car" to "电动车",
        "vtype_hybrid_car" to "混合动力车",
        "vtype_bicycle" to "自行车",
        "vtype_fleet" to "车队",
        "vtype_other" to "其他（自定义）",
        
        "total_vehicles" to "车辆总数",
        "upcoming_services" to "待办保养",
        "active_insurance" to "有效保险",
        "monthly_fuel_cost" to "本月燃油支出",
        "total_fuel_entries" to "加油记录总数",
        "vehicle_health_score" to "车辆健康指数",

        "status_active" to "有效",
        "status_expiring_soon" to "即将到期",
        "status_expired" to "已过期",
        "filter_all" to "全部",
        "insurance_policies_title" to "车辆保险",
        "insurance_policies_sub" to "保单详情、续保提醒与保障跟踪",
        "expense_manager_title" to "费用管理",
        "expense_manager_sub" to "记录停车、高速费、税费与维修费用",
        "timeline_title" to "车辆时间线",
        "gps_title" to "GPS 实时定位与行程",
        "family_sharing_title" to "家庭与共享驾驶员",
        "section_management" to "管理与服务",
        "section_preferences" to "应用偏好与工具",
        "cloud_account_offline" to "本地账户 (离线)",
        "cloud_sync_desc" to "登录以同步数据与多端备份",
        "btn_sign_in" to "登录",
        "btn_profile" to "个人资料",
        "user_profile_title" to "个人资料",
        "cloud_signin_title" to "云端账户登录",
        "analytics_cost_breakdown" to "费用分析与统计",
        "monthly_fuel_expenditure" to "每月燃油支出 ($)",
        "expense_category_breakdown" to "费用类别明细",
        "total_expense_logged" to "已记录总费用",
        "recent_timeline_activity" to "近期动态",
        "view_all" to "查看全部",
        "no_recent_activity" to "暂无近期动态记录。",
        "vehicles_active_fleet" to "车队活跃车辆",
        "tasks_pending" to "项待办任务",
        "all_tasks_up_to_date" to "所有任务均已最新",

        "got_it" to "知道了",
        "dont_show_again" to "不再显示",
        "reset_feature_guides" to "重置功能指南",
        "reset_feature_guides_desc" to "重新启用所有应用功能的首次介绍弹窗。",
        "guides_reset_toast" to "功能介绍指南已成功重置！",
        "guide_main_benefits" to "核心优势与功能",
        "guide_language_selector" to "指南语言",

        "guide_dashboard_title" to "仪表盘总览",
        "guide_dashboard_desc" to "您的车辆状态、费用汇总和近期动态的核心控制中心。",
        "guide_dashboard_benefits" to "• 查看车队健康指数与活跃车辆\n• 监控每月油耗与总支出\n• 使用行程费用预估与近期动态",

        "guide_garage_title" to "我的车辆（车库）",
        "guide_garage_desc" to "管理您的车辆档案、技术参数、里程表读数与健康状态。",
        "guide_garage_benefits" to "• 追踪车辆参数与车牌信息\n• 更新里程表读数\n• 生成并分享 PDF 车辆报告",

        "guide_fuel_title" to "油耗追踪",
        "guide_fuel_desc" to "记录加油日志、计算真实油耗 (km/L) 并监控加油站支出。",
        "guide_fuel_benefits" to "• 追踪燃油效率 (km/L)\n• 监控每公里行车成本\n• 分析每月加油站支出分析",

        "guide_services_title" to "保养记录",
        "guide_services_desc" to "记录更换机油、轮胎对调、刹车维修及未来保养计划。",
        "guide_services_benefits" to "• AI 智能保养建议\n• 详细记录修理厂与服务日志\n• 追踪零部件更换历史",

        "guide_expenses_title" to "费用管理",
        "guide_expenses_desc" to "追踪非加油类车辆开支，如停车费、高速费、税费与维修费。",
        "guide_expenses_benefits" to "• 分类整理停车、高速、税费与维修\n• 按车辆拆分支出明细\n• 可视化支出类别比例图表",

        "guide_documents_title" to "车辆证件",
        "guide_documents_desc" to "安全存储行驶证、驾驶证、环保标志与各类许可等。",
        "guide_documents_benefits" to "• 保存证件签发与到期日期\n• 到期预警标识与提醒\n• 随时随地查阅电子版证件",

        "guide_insurance_title" to "车辆保险",
        "guide_insurance_desc" to "追踪在保保单号、保障范围、保险专员电话与续保日期。",
        "guide_insurance_benefits" to "• 保单到期自动预警\n• 一键续保并自动计入费用\n• 一键拨打保险代理热线",

        "guide_reminders_title" to "提醒事项",
        "guide_reminders_desc" to "针对换油、轮胎检查、蓄电池检测与各种到期设定自定义提醒。",
        "guide_reminders_benefits" to "• 绝不错过关键车辆保养\n• 深度集成 Android 系统通知栏\n• 一键标记已完成状态",

        "guide_notifications_title" to "通知推送引擎",
        "guide_notifications_desc" to "通过 Android WorkManager 后台定时推送待办事项与预警。",
        "guide_notifications_benefits" to "• 保险与证件到期的系统级推送\n• 可自定义通知分类与开关\n• 应用关闭状态下依然后台监测",

        "guide_gps_tracking_title" to "GPS 实时定位",
        "guide_gps_tracking_desc" to "模拟车辆实时位置追踪、电子围栏预警与历史行程轨迹。",
        "guide_gps_tracking_benefits" to "• 地图实时查看车速与当前位置\n• 越界电子围栏触发报警\n• 历史行程路线深度分析",

        "guide_family_sharing_title" to "家庭与共享驾驶员",
        "guide_family_sharing_desc" to "与家庭成员共享车辆使用权、管理驾驶员档案并分配权限。",
        "guide_family_sharing_benefits" to "• 多用户共同管理车辆\n• 驾驶员档案与紧急联系方式\n• 无缝车辆转让与电子钥匙交接",

        "guide_settings_title" to "设置与偏好",
        "guide_settings_desc" to "自定义计量单位、货币符号、主题模式与云端数据库同步。",
        "guide_settings_benefits" to "• 多国货币 ($ € £ ₹ ¥) 与多语言切换\n• 明亮与深色主题模式切换\n• JSON 数据一键备份与还原",

        "open_battery_settings" to "打开电池设置",
        "configure_battery" to "配置电池设置",
        "enable_background_alerts" to "开启后台预警",
        "geofencing_enabled" to "电子围栏已启用",
        "status_label" to "状态",
        "fine_location" to "精确定位",
        "background_gps" to "后台 GPS",
        "exact_alarms" to "精确闹钟",
        "unrestricted_battery" to "无限制电池",
        "granted" to "已授权",
        "grant_location" to "授权定位",
        "allow_background" to "允许后台",
        "enable_alarms" to "开启闹钟",
        "geofence_all_met" to "已满足所有后台定位与闹钟规则",
        "geofence_bg_desc" to "开启后台追踪以在应用关闭时接收安全区域进出提醒。",
        "step_location" to "步骤 1: 位置权限",
        "step_bg_location" to "步骤 2: 后台位置权限",
        "step_exact_alarms" to "步骤 3: 精确闹钟",
        "step_battery" to "步骤 4: 电池优化引导",
        "battery_unrestricted_toast" to "电池设置：请设为“无限制”以确保及时预警。",
        "battery_manual_toast" to "请前往：系统设置 > 应用 > DriveCare > 电池 > 选择“无限制”",
        "done" to "完成",
        "skip_close" to "暂时跳过",
        "status_enabled" to "状态：已启用",
        "status_partially_enabled" to "状态：部分启用",
        "status_disabled" to "状态：未启用",
        "safe_zone_title" to "开启后台预警 (可选)",
        "safe_zone_sub" to "安全区域与边界追踪设置",
        "alerts_delayed_note" to "由于电池限制，预警可能会有所延迟。",
        "fine_location_desc" to "精确定位当前坐标并在地图上准确设置安全区域所需。",
        "bg_location_desc" to "即使在应用关闭时也能自动触发安全区域通知所需。",
        "exact_alarms_desc" to "用于按时调度精确的电子围栏边界检查与保养提醒。",
        "battery_guide_desc" to "防止系统休眠机制将后台监测挂起，提升预警可靠性。",
        "battery_optimization_disabled" to "已停用电池优化 ✓",

        "app_theme" to "应用主题",
        "back" to "返回",
        "system_default" to "跟随系统",
        "light_mode" to "浅色模式",
        "dark_mode" to "深色模式",
        "gps_hardware_trackers" to "GPS 追踪器设备",
        "gps_live_tracking" to "GPS 实时追踪",
        "location_history_logs" to "定位历史日志",
        "registered_trackers_count" to "%d 台已注册追踪器 • %d 台在线",
        "api_guide" to "API 指南",
        "no_trackers_registered" to "未注册 GPS 追踪器",
        "no_trackers_desc" to "通过 IMEI 和 SIM 卡号添加物理 GPS 追踪器设备。",
        "register_first_tracker" to "注册首个追踪器",
        "delete_tracker_title" to "删除 GPS 追踪器",
        "delete_tracker_confirm" to "确定要删除追踪器“%s”吗？",
        "hardware_integration_guide" to "硬件集成 API 指南",
        "imei_number" to "IMEI 编号",
        "sim_phone_number" to "SIM 卡手机号",
        "assigned_vehicle" to "关联车辆",
        "last_contact" to "最后在线",
        "never" to "从未",
        "live_map" to "实时地图",
        "history" to "历史轨迹",
        "register_new_tracker" to "注册新 GPS 追踪器",
        "edit_tracker" to "编辑 GPS 追踪器",
        "tracker_name_req" to "追踪器名称 *",
        "hardware_imei_req" to "硬件 IMEI 编号 *",
        "sim_card_phone" to "SIM 卡手机号码",
        "assign_to_vehicle" to "绑定车辆：",
        "notes_install_info" to "备注与安装信息",
        "save_tracker" to "保存追踪器",
        "status_online" to "在线",
        "status_offline" to "离线",
        "live_gps_fleet_tracking" to "GPS 车队实时追踪",
        "hardware_imei_label" to "硬件 IMEI：",
        "speed_label" to "车速：",
        "heading_label" to "航向：",
        "latitude_label" to "纬度：",
        "longitude_label" to "经度：",
        "geofence_safe_zones" to "电子围栏安全区",
        "add_safe_zone" to "添加安全区",
        "delete_safe_zone" to "删除安全区",
        "no_safe_zones_created" to "暂未创建安全区",
        "safe_zone_name" to "安全区名称",
        "radius_meters" to "半径 (米)",
        "location_coordinates" to "位置坐标",
        "speed_alert_threshold" to "超速预警阈值 (km/h)",
        "simulate_gps_movement" to "模拟 GPS 移动",
        "trigger_geofence_breach" to "触发电子围栏越界事件",
        "gps_tracker_management" to "GPS 追踪器管理",
        "simulation_mode_active" to "模拟模式已激活",
        "gps_location_history" to "GPS 定位历史记录",
        "filter_by_date_range" to "按日期范围筛选",
        "total_points_logged" to "已记录总点数",
        "total_distance_tracked" to "已追踪总距离",
        "max_speed_reached" to "最高行驶车速",
        "export_history_gpx_kml" to "导出历史轨迹 (GPX/KML)",
        "clear_history_logs" to "清空历史日志",
        "no_location_history_found" to "未找到该车辆的定位历史记录。",
        "timestamp" to "时间戳",
        "lat_lng" to "经纬度坐标",
        "speed" to "车速",
        "event_type" to "事件类型",
        "notif_service_due_title" to "保养到期提醒：%s",
        "notif_service_due_msg" to "%s 的保养项目需在 %s 前完成，请及时养护！",
        "notif_doc_expired_title" to "证件已过期：%s",
        "notif_doc_expired_msg" to "%s 车辆的 %s 证件已于 %s 过期，请立即续期！",
        "notif_doc_expiring_title" to "证件即将到期：%s",
        "notif_doc_expiring_msg" to "%s 车辆的 %s 证件将于 %s 到期。",
        "notif_ins_expired_title" to "车险已过期：%s",
        "notif_ins_expired_msg" to "保单号 #%s (%s) 已于 %s 过期！",
        "notif_ins_expiring_title" to "车险续保预警",
        "notif_ins_expiring_msg" to "%s 的保单 #%s 将在 30 天内到期 (%s)。",
        "notif_tracker_offline_title" to "GPS 追踪器离线预警",
        "notif_tracker_offline_msg" to "追踪器“%s”(IMEI: %s) 已静默超过 24 小时，请检查电源与 SIM 卡信号。",
        "notif_geofence_entered" to "进入安全区：%s",
        "notif_geofence_exited" to "离开安全区：%s",

        "management_services" to "管理与服务",
        "insurance_renewals_menu" to "保险与续保",
        "insurance_policies_sub" to "保险单、理赔和到期提醒",
        "expense_manager_menu" to "费用管理",
        "expense_manager_sub" to "跟踪车辆运营费用和明细",
        "vehicle_timeline_menu" to "车辆时间线",
        "vehicle_timeline_sub" to "加油、保养和事件的按时间顺序记录",
        "gps_hardware_menu" to "GPS 追踪设备",
        "gps_hardware_sub" to "管理硬件设备与 IMEI",
        "gps_live_tracking_menu" to "实时全球追踪",
        "gps_live_tracking_sub" to "实时位置、速度和坐标",
        "gps_location_history_menu" to "位置历史记录",
        "gps_location_history_sub" to "历史路线点和位置日志",
        "gps_tracking_menu" to "安全区域与地理围栏",
        "gps_tracking_sub" to "地理围栏边界警报与自动通知",
        "family_sharing_menu" to "家庭与多用户共享",
        "family_sharing_sub" to "向家人或司机授予车辆访问权限",
        "documents_sub" to "存储与跟踪车辆文件、证件和许可证",
        "emergency_sub" to "技师、道路救援与紧急联系人",
        "achievements_sub" to "安全驾驶徽章与环保保养",
        "app_preferences_tools" to "应用首选项与工具",
        "settings_sub" to "主题、通知、区域单位与安全",
        "current_language" to "当前语言",
        "backup_restore_sub" to "导出 JSON 备份或恢复记录",
        "about_drivecare_sub" to "2.0.0 全球版",
        "brand_showcase_title" to "品牌与 Logo 展示",
        "brand_showcase_sub" to "DriveCare 官方 Logo 与应用商店资产"
    )
}
