package com.drivecare.app.utils

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage(val displayName: String, val code: String, val isRtl: Boolean = false) {
    ENGLISH("English", "en"),
    URDU("اردو (Urdu)", "ur", isRtl = true),
    ARABIC("العربية (Arabic)", "ar", isRtl = true),
    HINDI("हिंदी (Hindi)", "hi"),
    CHINESE("简体中文 (Chinese)", "zh")
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }

object AppStrings {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> englishMap[key] ?: key
            AppLanguage.URDU -> urduMap[key] ?: englishMap[key] ?: key
            AppLanguage.ARABIC -> arabicMap[key] ?: englishMap[key] ?: key
            AppLanguage.HINDI -> hindiMap[key] ?: englishMap[key] ?: key
            AppLanguage.CHINESE -> chineseMap[key] ?: englishMap[key] ?: key
        }
    }

    private val englishMap = mapOf(
        "app_name" to "DriveCare",
        "tab_dashboard" to "Dashboard",
        "tab_garage" to "Garage",
        "tab_fuel" to "Fuel",
        "tab_services" to "Services",
        "tab_service" to "Services",
        "tab_more" to "More",
        "tab_documents" to "Documents",
        "tab_emergency" to "Emergency",
        "tab_achievements" to "Achievements",
        "tab_settings" to "Settings",
        "tab_reminders" to "Reminders",
        "backup_restore" to "Backup & Restore",
        
        "total_vehicles" to "Total Vehicles",
        "upcoming_services" to "Upcoming Services",
        "active_insurance" to "Active Insurance",
        "monthly_fuel_cost" to "Monthly Fuel Cost",
        "total_fuel_entries" to "Total Fuel Logs",
        "vehicle_health_score" to "Vehicle Health Score",
        
        "health_excellent" to "Excellent",
        "health_good" to "Good",
        "health_fair" to "Fair",
        "health_poor" to "Poor",
        
        "add_vehicle" to "Add Vehicle",
        "edit_vehicle" to "Edit Vehicle",
        "delete_vehicle" to "Delete Vehicle",
        "no_vehicles_title" to "No Vehicles Added Yet",
        "no_vehicles_desc" to "Tap the button below to add your first vehicle.",
        "vehicle_name" to "Vehicle Name",
        "brand" to "Brand",
        "model" to "Model",
        "year" to "Year",
        "plate_no" to "Plate No.",
        "fuel_type" to "Fuel Type",
        "odometer" to "Odometer Reading",
        "type" to "Vehicle Type",
        "fuel" to "Fuel",
        "plate" to "Plate",
        
        "log_fuel" to "Log Fuel",
        "select_vehicle" to "Select Vehicle",
        "all_vehicles" to "All Vehicles",
        "total_spent" to "Total Spent",
        "total_quantity" to "Total Quantity",
        "litres" to "Litres",
        "cost" to "Cost ($)",
        "gas_station" to "Gas Station (Optional)",
        "no_fuel_entries" to "No fuel entries found.",
        
        "add_service_log" to "Add Service Log",
        "service_title" to "Service Title (e.g. Oil Change)",
        "workshop" to "Workshop / Garage",
        "no_service_logs" to "No Service Logs Yet",
        "no_service_desc" to "Track oil changes, repairs, and tire rotations.",
        
        "add_reminder" to "Add Reminder",
        "reminder_title" to "Reminder Title (e.g. Insurance)",
        "due_date" to "Due Date",
        "no_reminders" to "No Service Reminders",
        "no_reminders_desc" to "Set reminders for insurance renewal, oil change, or inspection.",
        
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "confirm_delete_title" to "Delete Vehicle",
        "confirm_delete_msg" to "Are you sure you want to delete this vehicle? All associated logs will be removed.",
        "change_language" to "Change Language",
        
        "overview_title" to "DriveCare Overview",
        "pending_tasks" to "Pending Tasks",
        "fuel_spent" to "Fuel Spent",
        "service_spent" to "Service Spent",
        "fleet_summary" to "Quick Fleet Summary",
        "vehicles_count" to "Vehicles",
        "no_vehicles_registered" to "No registered vehicles in garage.",
        "trip_calculator" to "Trip Cost Estimator",
        "health_score" to "Vehicle Health",
        "calculate_trip" to "Calculate Trip Cost",
        "distance_km" to "Trip Distance (km)",
        "fuel_price" to "Fuel Price / Litre ($)",
        "avg_mileage" to "Average Mileage (km/L)",
        "estimated_cost" to "Estimated Cost",
        "passengers" to "Passengers Count",
        "cost_per_person" to "Cost Per Person",
        "calculate" to "Calculate",
        
        "advisor_title" to "Smart Maintenance Advisor",
        "advisor_subtitle" to "AI-powered maintenance suggestions based on mileage and history.",
        "oil_change_due" to "Engine Oil Replacement Recommended",
        "brake_inspection_due" to "Brake Pad Inspection Due",
        "air_filter_due" to "Air Filter Replacement Needed",
        "coolant_check_due" to "Coolant Fluid Level Check",
        "battery_check_due" to "Battery Health Check",
        "tire_rotation_due" to "Tire Rotation & Balancing",
        
        "vehicle_profile" to "Vehicle Profile",
        "export_pdf" to "Generate PDF Report",
        "share_pdf" to "Share Report",
        "pdf_generated" to "PDF Report Generated Successfully",
        
        "add_document" to "Add Document",
        "doc_type" to "Document Type",
        "issue_date" to "Issue Date",
        "expiry_date" to "Expiry Date",
        "no_documents" to "No Vehicle Documents Saved",
        
        "emergency_title" to "Roadside Emergency & Assistance",
        "one_tap_call" to "One-Tap Call",
        "mechanic" to "Mechanic",
        "family" to "Family Contact",
        "insurance_hotline" to "Insurance Hotline",
        "towing_service" to "Tow Truck Service",
        "add_contact" to "Add Emergency Contact",
        "no_contacts" to "No Emergency Contacts Added",
        
        "achievements_title" to "Achievements & Milestones",
        "first_vehicle" to "Pioneer: First Vehicle Added",
        "first_fuel" to "Pit Stop: First Fuel Entry Logged",
        "first_service" to "Mechanic Apprentice: First Service Logged",
        "distance_1000km" to "Road Tripper: 1,000 KM Driven",
        "distance_5000km" to "Highway Master: 5,000 KM Driven",
        "fuel_10_entries" to "Regular Refueler: 10 Fuel Entries",
        "fuel_25_entries" to "Fuel Tracker Pro: 25 Fuel Entries",
        "fuel_50_entries" to "Fleet Captain: 50 Fuel Entries",
        
        "settings_title" to "Settings & Preferences",
        "theme_mode" to "Dark Mode Theme",
        "language" to "Application Language",
        "backup_data" to "Backup Database (JSON)",
        "restore_data" to "Restore Database",
        "notifications" to "Service Notifications",
        "about_drivecare" to "DriveCare Version 2.0.0 (Global Edition)"
    )

    private val urduMap = mapOf(
        "app_name" to "ڈرائیو کیئر",
        "tab_dashboard" to "ڈیش بورڈ",
        "tab_garage" to "گیراج",
        "tab_fuel" to "ایندھن",
        "tab_services" to "سروسز",
        "tab_service" to "سروسز",
        "tab_more" to "مزید",
        "tab_documents" to "دستاویزات",
        "tab_emergency" to "ہنگامی مدد",
        "tab_achievements" to "کامیابیاں",
        "tab_settings" to "سیٹنگز",
        "tab_reminders" to "یاد دہانی",
        
        "total_vehicles" to "کل گاڑیاں",
        "upcoming_services" to "آنے والی سروسز",
        "active_insurance" to "فعال انشورنس",
        "monthly_fuel_cost" to "ماہانہ ایندھن کا خرچ",
        "total_fuel_entries" to "کل ایندھن کے ریکارڈ",
        "vehicle_health_score" to "گاڑی کی صحت کا اسکور",
        
        "health_excellent" to "بہترین",
        "health_good" to "اچھا",
        "health_fair" to "مناسب",
        "health_poor" to "کمزور",
        
        "add_vehicle" to "گاڑی شامل کریں",
        "edit_vehicle" to "گاڑی تبدیل کریں",
        "delete_vehicle" to "گاڑی ختم کریں",
        "no_vehicles_title" to "ابھی تک کوئی گاڑی شامل نہیں کی گئی",
        "no_vehicles_desc" to "اپنی پہلی گاڑی شامل کرنے کے لیے بٹن پر کلک کریں۔",
        "vehicle_name" to "گاڑی کا نام",
        "brand" to "کمپنی / برانڈ",
        "model" to "ماڈل",
        "year" to "سال",
        "plate_no" to "نمبر پلیٹ",
        "fuel_type" to "ایندھن کی قسم",
        "odometer" to "میٹر ریڈنگ (کلو میٹر)",
        "type" to "گاڑی کی قسم",
        
        "log_fuel" to "ایندھن درج کریں",
        "select_vehicle" to "گاڑی منتخب کریں",
        "all_vehicles" to "تمام گاڑیاں",
        "total_spent" to "کل خرچ",
        "total_quantity" to "کل مقدار (لیٹر)",
        "litres" to "لیٹر",
        "cost" to "قیمت ($)",
        "gas_station" to "پیٹرول پمپ",
        
        "add_service_log" to "سروس درج کریں",
        "service_title" to "تفصیل (مثلاً آئل چینج)",
        "workshop" to "ورکشاپ",
        "no_service_logs" to "کوئی سروس ریکارڈ نہیں",
        
        "add_reminder" to "یاد دہانی لگائیں",
        "due_date" to "تاریخ",
        "save" to "محفوظ کریں",
        "cancel" to "منسوخ کریں",
        "delete" to "ختم کریں",
        
        "advisor_title" to "سمارٹ سروس مشیر",
        "advisor_subtitle" to "گاڑی کی کلومیٹر اور ہسٹری کے مطابق خودکار تجاویز۔",
        "oil_change_due" to "انجن آئل تبدیل کرنے کی ضرورت ہے",
        "brake_inspection_due" to "بریک پیڈز کی چیکنگ ضروری ہے",
        "air_filter_due" to "ایئر فلٹر تبدیل کریں",
        "coolant_check_due" to "کولنٹ لیول چیک کریں",
        "battery_check_due" to "بیٹری کی حالت چیک کریں",
        "tire_rotation_due" to "ٹائر روٹیشن اور بیلنسنگ",
        
        "vehicle_profile" to "گاڑی کا پروفائل",
        "export_pdf" to "پی ڈی ایف رپورٹ بنائیں",
        "share_pdf" to "رپورٹ شیئر کریں",
        
        "add_document" to "دستاویز شامل کریں",
        "doc_type" to "دستاویز کی قسم",
        "emergency_title" to "روڈ سائیڈ ایمرجنسی مدد",
        "one_tap_call" to "ایک ٹیپ سے کال کریں",
        "mechanic" to "مکینک",
        "family" to "اہل خانہ",
        "insurance_hotline" to "انشورنس ہیلپ لائن",
        "towing_service" to "ٹو ٹرک سروس",
        
        "achievements_title" to "کامیابیاں اور ایوارڈز",
        "settings_title" to "ایپ سیٹنگز",
        "theme_mode" to "ڈارک موڈ",
        "language" to "زبان کا انتخاب",
        "backup_data" to "بیک اپ لیں (JSON)",
        "restore_data" to "ریسٹور کریں",
        "notifications" to "نوٹیفیکیشنز"
    )

    private val arabicMap = mapOf(
        "app_name" to "درايف كير",
        "tab_dashboard" to "لوحة التحكم",
        "tab_garage" to "المرأب",
        "tab_fuel" to "الوقود",
        "tab_services" to "الصيانة",
        "tab_service" to "الصيانة",
        "tab_more" to "المزيد",
        "tab_documents" to "الوثائق",
        "tab_emergency" to "الطوارئ",
        "tab_achievements" to "الإنجازات",
        "tab_settings" to "الإعدادات",
        "tab_reminders" to "التذكيرات",
        
        "total_vehicles" to "إجمالي المركبات",
        "upcoming_services" to "الصيانة القادمة",
        "active_insurance" to "التأمين النشط",
        "monthly_fuel_cost" to "تكلفة الوقود الشهرية",
        "total_fuel_entries" to "سجلات الوقود",
        "vehicle_health_score" to "مؤشر صحة المركبة",
        
        "health_excellent" to "ممتاز",
        "health_good" to "جيد",
        "health_fair" to "مقبول",
        "health_poor" to "ضعيف",
        
        "add_vehicle" to "إضافة مركبة",
        "edit_vehicle" to "تعديل المركبة",
        "delete_vehicle" to "حذف المركبة",
        "no_vehicles_title" to "لم يتم إضافة مركبات بعد",
        "no_vehicles_desc" to "اضغط على الزر أدناه لإضافة أول مركبة.",
        "vehicle_name" to "اسم المركبة",
        "brand" to "الماركة",
        "model" to "الموديل",
        "year" to "السنة",
        "plate_no" to "رقم لوحة السيارة",
        "fuel_type" to "نوع الوقود",
        "odometer" to "قراءة العداد (كم)",
        
        "log_fuel" to "تسجيل الوقود",
        "select_vehicle" to "اختر المركبة",
        "all_vehicles" to "جميع المركبات",
        "total_spent" to "المبلغ الإجمالي",
        "total_quantity" to "الكمية الإجمالية",
        "litres" to "لتر",
        "cost" to "التكلفة ($)",
        
        "add_service_log" to "إضافة سجل صيانة",
        "service_title" to "نوع الخدمة (مثل تغيير الزيت)",
        "workshop" to "الورشة / الكراج",
        
        "advisor_title" to "مستشار الصيانة الذكي",
        "advisor_subtitle" to "توصيات صيانة ذكية بناءً على الكيلومترات والسجل.",
        "oil_change_due" to "يوصى بتغيير زيت المحرك",
        "brake_inspection_due" to "فحص فحمات الفرامل مطلوب",
        "air_filter_due" to "تغيير فلتر الهواء مطلوب",
        "coolant_check_due" to "فحص مستوى سائل التبريد",
        "battery_check_due" to "فحص حالة البطارية",
        "tire_rotation_due" to "تدوير وترصيص الإطارات",
        
        "vehicle_profile" to "ملف المركبة",
        "export_pdf" to "إنشاء تقرير PDF",
        "share_pdf" to "مشاركة التقرير",
        "add_document" to "إضافة وثيقة",
        "doc_type" to "نوع الوثيقة",
        "emergency_title" to "طوارئ الطريق والمساعدة",
        "one_tap_call" to "اتصال بضغطة واحدة",
        "mechanic" to "الميكانيكي",
        "family" to "جهة اتصال العائلة",
        "insurance_hotline" to "خط طوارئ التأمين",
        "towing_service" to "سطحة / سحب السيارات",
        
        "achievements_title" to "الإنجازات والميداليات",
        "settings_title" to "الإعدادات والتفضيلات",
        "theme_mode" to "الوضع الداكن",
        "language" to "لغة التطبيق",
        "backup_data" to "نسخ احتياطي (JSON)",
        "restore_data" to "استعادة البيانات"
    )

    private val hindiMap = mapOf(
        "app_name" to "ड्राइवकेयर",
        "tab_dashboard" to "डैशबोर्ड",
        "tab_garage" to "गैरेज",
        "tab_fuel" to "ईंधन",
        "tab_services" to "सर्विस",
        "tab_service" to "सर्विस",
        "tab_more" to "अन्य",
        "tab_documents" to "दस्तावेज़",
        "tab_emergency" to "आपातकालीन सेवा",
        "tab_achievements" to "उपलब्धियां",
        "tab_settings" to "सेटिंग्स",
        "tab_reminders" to "रिमाइंडर",
        
        "total_vehicles" to "कुल वाहन",
        "upcoming_services" to "आगामी सर्विस",
        "active_insurance" to "सक्रिय बीमा",
        "monthly_fuel_cost" to "मासिक ईंधन खर्च",
        "total_fuel_entries" to "कुल ईंधन लॉग",
        "vehicle_health_score" to "वाहन स्वास्थ्य स्कोर",
        
        "health_excellent" to "उत्कृष्ट",
        "health_good" to "अच्छा",
        "health_fair" to "सामान्य",
        "health_poor" to "कमजोर",
        
        "add_vehicle" to "वाहन जोड़ें",
        "edit_vehicle" to "वाहन बदलें",
        "delete_vehicle" to "वाहन हटाएं",
        "no_vehicles_title" to "कोई वाहन नहीं जोड़ा गया",
        "no_vehicles_desc" to "अपना पहला वाहन जोड़ने के लिए नीचे दिए गए बटन पर टैप करें।",
        "vehicle_name" to "वाहन का नाम",
        "brand" to "ब्रांड",
        "model" to "मॉडल",
        "year" to "वर्ष",
        "plate_no" to "नंबर प्लेट",
        "fuel_type" to "ईंधन का प्रकार",
        "odometer" to "ओडोमीटर रीडिंग (किमी)",
        
        "log_fuel" to "ईंधन लॉग करें",
        "select_vehicle" to "वाहन चुनें",
        "all_vehicles" to "सभी वाहन",
        "total_spent" to "कुल खर्च",
        "total_quantity" to "कुल मात्रा (लीटर)",
        
        "add_service_log" to "सर्विस लॉग जोड़ें",
        "service_title" to "सर्विस का शीर्षक (जैसे ऑयल चेंज)",
        "workshop" to "वर्कशॉप / गैरेज",
        
        "advisor_title" to "स्मार्ट सर्विस एडवाइजर",
        "advisor_subtitle" to "किलोमीटर और इतिहास के आधार पर एआई सिफारिशें।",
        "oil_change_due" to "इंजन ऑयल बदलने की आवश्यकता है",
        "brake_inspection_due" to "ब्रेक पैड जांच आवश्यक",
        "air_filter_due" to "एयर फ़िल्टर बदलें",
        "coolant_check_due" to "कूलेंट द्रव स्तर जांचें",
        "battery_check_due" to "बैटरी स्वास्थ्य जांच",
        "tire_rotation_due" to "टायर रोटेशन और बैलेंसिंग",
        
        "vehicle_profile" to "वाहन प्रोफ़ाइल",
        "export_pdf" to "पीडीएफ रिपोर्ट बनाएं",
        "share_pdf" to "रिपोर्ट शेयर करें",
        "add_document" to "दस्तावेज़ जोड़ें",
        "emergency_title" to "आपातकालीन सहायता",
        "one_tap_call" to "एक टैप कॉल",
        "mechanic" to "मैकेनिक",
        "family" to "परिवार",
        "insurance_hotline" to "बीमा हेल्पलाइन",
        "towing_service" to "टोइंग सेवा",
        
        "achievements_title" to "उपलब्धियां",
        "settings_title" to "सेटिंग्स",
        "theme_mode" to "डार्क मोड",
        "language" to "भाषा",
        "backup_data" to "बैकअप (JSON)",
        "restore_data" to "रिस्टोर"
    )

    private val chineseMap = mapOf(
        "app_name" to "DriveCare 驭管家",
        "tab_dashboard" to "仪表盘",
        "tab_garage" to "我的车库",
        "tab_fuel" to "油耗",
        "tab_services" to "保养",
        "tab_service" to "保养",
        "tab_more" to "更多",
        "tab_documents" to "车辆证件",
        "tab_emergency" to "紧急救援",
        "tab_achievements" to "里程成就",
        "tab_settings" to "设置",
        "tab_reminders" to "提醒事项",
        
        "total_vehicles" to "车辆总数",
        "upcoming_services" to "待办保养",
        "active_insurance" to "有效保险",
        "monthly_fuel_cost" to "本月燃油支出",
        "total_fuel_entries" to "加油记录总数",
        "vehicle_health_score" to "车辆健康指数",
        
        "health_excellent" to "极佳",
        "health_good" to "良好",
        "health_fair" to "一般",
        "health_poor" to "较差",
        
        "add_vehicle" to "添加车辆",
        "edit_vehicle" to "编辑车辆",
        "delete_vehicle" to "删除车辆",
        "no_vehicles_title" to "暂未添加任何车辆",
        "no_vehicles_desc" to "点击下方按钮添加您的第一辆爱车。",
        "vehicle_name" to "车辆名称",
        "brand" to "品牌",
        "model" to "车型",
        "year" to "年份",
        "plate_no" to "车牌号码",
        "fuel_type" to "燃料类型",
        "odometer" to "里程表读数 (km)",
        
        "log_fuel" to "记录加油",
        "select_vehicle" to "选择车辆",
        "all_vehicles" to "所有车辆",
        "total_spent" to "总支出",
        "total_quantity" to "总加油量 (升)",
        
        "add_service_log" to "添加保养记录",
        "service_title" to "保养项目 (例如 机油更换)",
        "workshop" to "修理厂 / 4S店",
        
        "advisor_title" to "智能保养顾问",
        "advisor_subtitle" to "基于行驶里程与历史记录的智能保养建议。",
        "oil_change_due" to "建议更换发动机机油",
        "brake_inspection_due" to "需检查刹车片磨损",
        "air_filter_due" to "建议更换空气滤清器",
        "coolant_check_due" to "检查冷却液液位",
        "battery_check_due" to "检查蓄电池健康状况",
        "tire_rotation_due" to "轮胎换位与动平衡",
        
        "vehicle_profile" to "车辆详情档案",
        "export_pdf" to "生成 PDF 导出报告",
        "share_pdf" to "分享 PDF 报告",
        "add_document" to "添加车辆证件",
        "emergency_title" to "道路紧急救援",
        "one_tap_call" to "一键拨号",
        "mechanic" to "修理厂",
        "family" to "紧急联系人",
        "insurance_hotline" to "保险报案热线",
        "towing_service" to "拖车救援",
        
        "achievements_title" to "成就与里程碑",
        "settings_title" to "系统设置",
        "theme_mode" to "深色模式",
        "language" to "应用语言",
        "backup_data" to "数据备份 (JSON)",
        "restore_data" to "恢复数据"
    )
}
