package com.drivecare.app.utils

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val displayName: String, val code: String, val isRtl: Boolean = false) {
    ENGLISH("English", "en"),
    URDU("اردو (Urdu)", "ur", isRtl = true),
    ARABIC("العربية (Arabic)", "ar", isRtl = true),
    HINDI("हिंदी (Hindi)", "hi"),
    CHINESE("简体中文 (Chinese)", "zh")
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }

object AppStrings {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.ENGLISH -> englishMap[key] ?: key
            AppLanguage.URDU -> urduMap[key] ?: englishMap[key] ?: key
            AppLanguage.ARABIC -> arabicMap[key] ?: englishMap[key] ?: key
            AppLanguage.HINDI -> hindiMap[key] ?: englishMap[key] ?: key
            AppLanguage.CHINESE -> chineseMap[key] ?: englishMap[key] ?: key
        }
    }

    private val englishMap = mapOf(
        "app_name" to "DriveCare",
        "tab_dashboard" to "Dashboard",
        "tab_garage" to "Garage",
        "tab_fuel" to "Fuel",
        "tab_services" to "Services",
        "tab_service" to "Services",
        "tab_more" to "More",
        "tab_documents" to "Documents",
        "tab_emergency" to "Emergency",
        "tab_achievements" to "Achievements",
        "tab_settings" to "Settings",
        "tab_reminders" to "Reminders",
        "backup_restore" to "Backup & Restore",
        
        "total_vehicles" to "Total Vehicles",
        "upcoming_services" to "Upcoming Services",
        "active_insurance" to "Active Insurance",
        "monthly_fuel_cost" to "Monthly Fuel Cost",
        "total_fuel_entries" to "Total Fuel Logs",
        "vehicle_health_score" to "Vehicle Health Score",
        
        "health_excellent" to "Excellent",
        "health_good" to "Good",
        "health_fair" to "Fair",
        "health_poor" to "Poor",
        
        "add_vehicle" to "Add Vehicle",
        "edit_vehicle" to "Edit Vehicle",
        "delete_vehicle" to "Delete Vehicle",
        "no_vehicles_title" to "No Vehicles Added Yet",
        "no_vehicles_desc" to "Tap the button below to add your first vehicle.",
        "vehicle_name" to "Vehicle Name",
        "brand" to "Brand",
        "model" to "Model",
        "year" to "Year",
        "plate_no" to "Plate No.",
        "fuel_type" to "Fuel Type",
        "odometer" to "Odometer Reading",
        "type" to "Vehicle Type",
        "fuel" to "Fuel",
        "plate" to "Plate",
        
        "log_fuel" to "Log Fuel",
        "select_vehicle" to "Select Vehicle",
        "all_vehicles" to "All Vehicles",
        "total_spent" to "Total Spent",
        "total_quantity" to "Total Quantity",
        "litres" to "Litres",
        "cost" to "Cost ($)",
        "gas_station" to "Gas Station (Optional)",
        "no_fuel_entries" to "No fuel entries found.",
        
        "add_service_log" to "Add Service Log",
        "service_title" to "Service Title (e.g. Oil Change)",
        "workshop" to "Workshop / Garage",
        "no_service_logs" to "No Service Logs Yet",
        "no_service_desc" to "Track oil changes, repairs, and tire rotations.",
        
        "add_reminder" to "Add Reminder",
        "reminder_title" to "Reminder Title (e.g. Insurance)",
        "due_date" to "Due Date",
        "no_reminders" to "No Service Reminders",
        "no_reminders_desc" to "Set reminders for insurance renewal, oil change, or inspection.",
        
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "confirm_delete_title" to "Delete Vehicle",
        "confirm_delete_msg" to "Are you sure you want to delete this vehicle? All associated logs will be removed.",
        "change_language" to "Change Language",
        
        "overview_title" to "DriveCare Overview",
        "pending_tasks" to "Pending Tasks",
        "fuel_spent" to "Fuel Spent",
        "service_spent" to "Service Spent",
        "fleet_summary" to "Quick Fleet Summary",
        "vehicles_count" to "Vehicles",
        "no_vehicles_registered" to "No registered vehicles in garage.",
        "trip_calculator" to "Trip Cost Estimator",
        "health_score" to "Vehicle Health",
        "calculate_trip" to "Calculate Trip Cost",
        "distance_km" to "Trip Distance (km)",
        "fuel_price" to "Fuel Price / Litre ($)",
        "avg_mileage" to "Average Mileage (km/L)",
        "estimated_cost" to "Estimated Cost",
        "passengers" to "Passengers Count",
        "cost_per_person" to "Cost Per Person",
        "calculate" to "Calculate",
        
        "advisor_title" to "Smart Maintenance Advisor",
        "advisor_subtitle" to "AI-powered maintenance suggestions based on mileage and history.",
        "oil_change_due" to "Engine Oil Replacement Recommended",
        "brake_inspection_due" to "Brake Pad Inspection Due",
        "air_filter_due" to "Air Filter Replacement Needed",
        "coolant_check_due" to "Coolant Fluid Level Check",
        "battery_check_due" to "Battery Health Check",
        "tire_rotation_due" to "Tire Rotation & Balancing",
        
        "vehicle_profile" to "Vehicle Profile",
        "export_pdf" to "Generate PDF Report",
        "share_pdf" to "Share Report",
        "pdf_generated" to "PDF Report Generated Successfully",
        
        "add_document" to "Add Document",
        "doc_type" to "Document Type",
        "issue_date" to "Issue Date",
        "expiry_date" to "Expiry Date",
        "no_documents" to "No Vehicle Documents Saved",
        
        "emergency_title" to "Roadside Emergency & Assistance",
        "one_tap_call" to "One-Tap Call",
        "mechanic" to "Mechanic",
        "family" to "Family Contact",
        "insurance_hotline" to "Insurance Hotline",
        "towing_service" to "Tow Truck Service",
        "add_contact" to "Add Emergency Contact",
        "no_contacts" to "No Emergency Contacts Added",
        
        "achievements_title" to "Achievements & Milestones",
        "first_vehicle" to "Pioneer: First Vehicle Added",
        "first_fuel" to "Pit Stop: First Fuel Entry Logged",
        "first_service" to "Mechanic Apprentice: First Service Logged",
        "distance_1000km" to "Road Tripper: 1,000 KM Driven",
        "distance_5000km" to "Highway Master: 5,000 KM Driven",
        "fuel_10_entries" to "Regular Refueler: 10 Fuel Entries",
        "fuel_25_entries" to "Fuel Tracker Pro: 25 Fuel Entries",
        "fuel_50_entries" to "Fleet Captain: 50 Fuel Entries",
        
        "settings_title" to "Settings & Preferences",
        "theme_mode" to "Dark Mode Theme",
        "language" to "Application Language",
        "backup_data" to "Backup Database (JSON)",
        "restore_data" to "Restore Database",
        "notifications" to "Service Notifications",
        "about_drivecare" to "DriveCare Version 2.0.0 (Global Edition)",

        // New localization keys for complete translation
        "analytics_cost_breakdown" to "Analytics & Cost Breakdown",
        "monthly_fuel_expenditure" to "Monthly Fuel Expenditure ($)",
        "expense_category_breakdown" to "Expense Category Breakdown",
        "total_expense_logged" to "Total Expense Logged",
        "recent_timeline_activity" to "Recent Timeline Activity",
        "view_all" to "View All",
        "no_recent_activity" to "No recent activity logged yet. Refuel or log maintenance to see history.",
        "vehicles_active_fleet" to "Vehicles Active in Fleet",
        "tasks_pending" to "tasks pending",
        "all_tasks_up_to_date" to "All tasks up to date",
        "fleet_health_label" to "Fleet Health",
        "fuel_efficiency" to "Fuel Efficiency",
        "cost_label" to "Cost",

        "insurance_policies_title" to "Insurance & Policies",
        "insurance_policies_sub" to "Policy Details, Renewal Reminders & Coverage Tracking",
        "status_active" to "Active",
        "status_expiring_soon" to "Expiring Soon",
        "status_expired" to "Expired",
        "filter_all" to "All",
        "filter_expiring" to "Expiring",
        "no_policies_found" to "No Insurance Policies Found",
        "no_policies_desc" to "Tap the + button below to add your vehicle insurance policy and set renewal reminders.",
        "policy_no_prefix" to "Policy #",
        "vehicle_linked" to "Vehicle Linked",
        "coverage_type" to "Coverage Type",
        "premium" to "Premium",
        "valid_period" to "Valid",
        "auto_renew_on" to "Auto-Renew On",
        "btn_renew" to "Renew",
        "btn_agent" to "Agent",
        "add_policy_title" to "Add Insurance Policy",
        "edit_policy_title" to "Edit Insurance Policy",
        "provider_name" to "Insurance Provider Name",
        "policy_number" to "Policy Number",
        "start_date" to "Start Date",
        "agent_phone" to "Agent Phone / Hotline",
        "notes_info" to "Notes / Deductible Info",
        "enable_autorenew" to "Enable Auto-Renew Flag",
        "save_policy" to "Save Policy",
        "update_policy" to "Update Policy",
        "renew_policy_title" to "Renew Policy #",
        "new_start_date" to "New Start Date",
        "new_expiry_date" to "New Expiry Date",
        "renewal_premium" to "Renewal Premium Amount",
        "confirm_renewal" to "Confirm Renewal & Log Expense",
        "delete_policy_title" to "Delete Insurance Policy",

        "expense_manager_title" to "Expense Manager",
        "expense_manager_sub" to "Track Parking, Tolls, Taxes, Insurance & Repairs",
        "total_vehicle_expenses" to "Total Vehicle Expenses",
        "category_breakdown" to "Category Breakdown",
        "expense_history" to "Expense History",
        "no_expenses_found" to "No Expenses Logged Yet",
        "no_expenses_desc" to "Tap '+ Add Expense' to log parking, tolls, taxes, or insurance.",
        "add_expense" to "Add Expense",
        "log_new_expense" to "Log New Expense",
        "expense_title" to "Expense Title",
        "category" to "Category",
        "amount" to "Amount",
        "date" to "Date",

        "timeline_title" to "Vehicle Timeline",
        "timeline_sub" to "Chronological Activity Stream Across Refills, Services & Expenses",
        "no_timeline_found" to "No Timeline Events Found",

        "gps_title" to "GPS Live Tracking & Trip Logs",
        "gps_sub" to "Real-time Location, Geofencing & Route History",

        "family_sharing_title" to "Family Sharing & Drivers",
        "family_sharing_sub" to "Multi-User Vehicle Sharing, Driver Profiles & Transfers",

        "section_management" to "MANAGEMENT & SERVICES",
        "section_preferences" to "APP PREFERENCES & TOOLS",
        "cloud_account_offline" to "Local Account (Offline)",
        "cloud_sync_desc" to "Sign in to backup & sync data across devices",
        "btn_sign_in" to "Sign In",
        "btn_profile" to "Profile",
        "user_profile_title" to "User Profile",
        "cloud_signin_title" to "Cloud Account Sign In",

        "got_it" to "Got It",
        "dont_show_again" to "Don't Show Again",
        "reset_feature_guides" to "Reset Feature Guides",
        "reset_feature_guides_desc" to "Re-enable first-time introduction popups for all app features.",
        "guides_reset_toast" to "Feature introduction guides reset successfully!",
        "guide_main_benefits" to "Key Benefits & Capabilities",
        "guide_language_selector" to "Guide Language",

        "guide_dashboard_title" to "Dashboard Overview",
        "guide_dashboard_desc" to "Your central command center for fleet status, expense summaries, and recent activity.",
        "guide_dashboard_benefits" to "• View fleet health score & active vehicles\n• Monitor monthly fuel & total expenses\n• Access trip cost estimator & recent timeline",

        "guide_garage_title" to "My Vehicles (Garage)",
        "guide_garage_desc" to "Manage your vehicle profiles, specifications, odometer readings, and health status.",
        "guide_garage_benefits" to "• Track vehicle specs & license plates\n• Update mileage and odometer readings\n• Generate & share PDF vehicle reports",

        "guide_fuel_title" to "Fuel Tracker",
        "guide_fuel_desc" to "Log gas refuels, calculate real fuel efficiency, and monitor gas station expenses.",
        "guide_fuel_benefits" to "• Track fuel consumption (km/L)\n• Monitor cost per kilometer\n• Analyze monthly gas station expenditure",

        "guide_services_title" to "Maintenance History",
        "guide_services_desc" to "Record oil changes, tire rotations, brake repairs, and upcoming service schedules.",
        "guide_services_benefits" to "• AI smart maintenance recommendations\n• Keep detailed workshop & service logs\n• Track parts replacement history",

        "guide_expenses_title" to "Expense Manager",
        "guide_expenses_desc" to "Track non-fuel vehicle expenses like parking, highway tolls, taxes, and repairs.",
        "guide_expenses_benefits" to "• Categorize parking, tolls, taxes & repairs\n• Expense breakdown per vehicle\n• Visual spending category progress charts",

        "guide_documents_title" to "Vehicle Documents",
        "guide_documents_desc" to "Store registration certificates, PUC licenses, driver's licenses, and permits securely.",
        "guide_documents_benefits" to "• Save issue & expiry dates for documents\n• Expiry warning badges and alerts\n• Keep digital document access on the go",

        "guide_insurance_title" to "Insurance Policies",
        "guide_insurance_desc" to "Track active policy numbers, coverage details, agent hotlines, and renewal dates.",
        "guide_insurance_benefits" to "• Automatic policy expiration warnings\n• One-tap renewal & expense logging\n• Direct agent hotline calling",

        "guide_reminders_title" to "Service Reminders",
        "guide_reminders_desc" to "Set custom due dates for oil changes, tire inspection, battery checks, and renewals.",
        "guide_reminders_benefits" to "• Never miss critical maintenance tasks\n• Integrated with Android system notifications\n• Quick mark completed status",

        "guide_notifications_title" to "Notification Engine",
        "guide_notifications_desc" to "Automated background alerts delivered via Android WorkManager for pending tasks.",
        "guide_notifications_benefits" to "• System alerts for expiring insurance & docs\n• Customizable notification categories\n• Background check even when app is closed",

        "guide_gps_tracking_title" to "GPS Live Tracking",
        "guide_gps_tracking_desc" to "Simulate live vehicle location tracking, geofence alerts, and trip route logs.",
        "guide_gps_tracking_benefits" to "• View live map location & speed\n• Geofence boundary breach alerts\n• Historical trip route analysis",

        "guide_family_sharing_title" to "Family Sharing & Drivers",
        "guide_family_sharing_desc" to "Share vehicle access with family members, manage driver profiles, and assign permissions.",
        "guide_family_sharing_benefits" to "• Multi-user vehicle sharing\n• Driver profiles & contact details\n• Seamless ownership & key transfers",

        "guide_settings_title" to "Settings & Preferences",
        "guide_settings_desc" to "Customize regional units, currency symbols, theme modes, and cloud database sync.",
        "guide_settings_benefits" to "• Multi-currency ($ € £ ₹ ¥) & language options\n• Light & Dark theme preferences\n• JSON data backup & restore"
    )

    private val urduMap = mapOf(
        "app_name" to "ڈرائیو کیئر",
        "tab_dashboard" to "ڈیش بورڈ",
        "tab_garage" to "گیراج",
        "tab_fuel" to "ایندھن",
        "tab_services" to "سروسز",
        "tab_service" to "سروسز",
        "tab_more" to "مزید",
        "tab_documents" to "دستاویزات",
        "tab_emergency" to "ہنگامی مدد",
        "tab_achievements" to "کامیابیاں",
        "tab_settings" to "سیٹنگز",
        "tab_reminders" to "یاد دہانی",
        "backup_restore" to "بیک اپ اور ری سٹور",
        
        "total_vehicles" to "کل گاڑیاں",
        "upcoming_services" to "آنے والی سروسز",
        "active_insurance" to "فعال انشورنس",
        "monthly_fuel_cost" to "ماہانہ ایندھن کا خرچ",
        "total_fuel_entries" to "کل ایندھن کے ریکارڈ",
        "vehicle_health_score" to "گاڑی کی صحت کا اسکور",
        
        "health_excellent" to "بہترین",
        "health_good" to "اچھا",
        "health_fair" to "مناسب",
        "health_poor" to "کمزور",
        
        "add_vehicle" to "گاڑی شامل کریں",
        "edit_vehicle" to "گاڑی تبدیل کریں",
        "delete_vehicle" to "گاڑی ختم کریں",
        "no_vehicles_title" to "ابھی تک کوئی گاڑی شامل نہیں کی گئی",
        "no_vehicles_desc" to "اپنی پہلی گاڑی شامل کرنے کے لیے بٹن پر کلک کریں۔",
        "vehicle_name" to "گاڑی کا نام",
        "brand" to "کمپنی / برانڈ",
        "model" to "ماڈل",
        "year" to "سال",
        "plate_no" to "نمبر پلیٹ",
        "fuel_type" to "ایندھن کی قسم",
        "odometer" to "میٹر ریڈنگ (کلو میٹر)",
        "type" to "گاڑی کی قسم",
        "fuel" to "ایندھن",
        "plate" to "نمبر پلیٹ",
        
        "log_fuel" to "ایندھن درج کریں",
        "select_vehicle" to "گاڑی منتخب کریں",
        "all_vehicles" to "تمام گاڑیاں",
        "total_spent" to "کل خرچ",
        "total_quantity" to "کل مقدار (لیٹر)",
        "litres" to "لیٹر",
        "cost" to "قیمت ($)",
        "gas_station" to "پیٹرول پمپ",
        "no_fuel_entries" to "ایندھن کا کوئی ریکارڈ نہیں مل سکا۔",
        
        "add_service_log" to "سروس درج کریں",
        "service_title" to "تفصیل (مثلاً آئل چینج)",
        "workshop" to "ورکشاپ",
        "no_service_logs" to "کوئی سروس ریکارڈ نہیں",
        "no_service_desc" to "آئل چینج اور ٹیوننگ کا ہسٹری ٹریک کریں۔",
        
        "add_reminder" to "یاد دہانی لگائیں",
        "reminder_title" to "عنوان",
        "due_date" to "تاریخ",
        "no_reminders" to "کوئی یاد دہانی نہیں",
        "no_reminders_desc" to "انشورنس اور سروس کے لیے یاد دہانی سیٹ کریں۔",
        
        "save" to "محفوظ کریں",
        "cancel" to "منسوخ کریں",
        "delete" to "ختم کریں",
        "confirm_delete_title" to "گاڑی ختم کریں",
        "confirm_delete_msg" to "کیا آپ یقینی طور پر اس گاڑی کو ڈلیٹ کرنا چاہتے ہیں؟",
        "change_language" to "زبان تبدیل کریں",
        
        "overview_title" to "ڈرائیو کیئر جائزہ",
        "pending_tasks" to "بقیہ کام",
        "fuel_spent" to "ایندھن کا خرچ",
        "service_spent" to "سروس کا خرچ",
        "fleet_summary" to "گاڑیوں کی حالت کا جائزہ",
        "vehicles_count" to "گاڑیاں",
        "no_vehicles_registered" to "گیراج میں کوئی گاڑی درج نہیں ہے۔",
        "trip_calculator" to "سفر کے اخراجات کا اندازہ",
        "health_score" to "گاڑی کی صحت",
        "calculate_trip" to "حساب لگائیں",
        "distance_km" to "سفر کا فاصلہ (کلو میٹر)",
        "fuel_price" to "ایندھن کی قیمت فی لیٹر ($)",
        "avg_mileage" to "اوسط مائلیج (km/L)",
        "estimated_cost" to "متوقع خرچ",
        "passengers" to "مسافروں کی تعداد",
        "cost_per_person" to "فی کس خرچ",
        "calculate" to "حساب لگائیں",
        
        "advisor_title" to "سمارٹ سروس مشیر",
        "advisor_subtitle" to "گاڑی کی کلومیٹر اور ہسٹری کے مطابق خودکار تجاویز۔",
        "oil_change_due" to "انجن آئل تبدیل کرنے کی ضرورت ہے",
        "brake_inspection_due" to "بریک پیڈز کی چیکنگ ضروری ہے",
        "air_filter_due" to "ایئر فلٹر تبدیل کریں",
        "coolant_check_due" to "کولنٹ لیول چیک کریں",
        "battery_check_due" to "بیٹری کی حالت چیک کریں",
        "tire_rotation_due" to "ٹائر روٹیشن اور بیلنسنگ",
        
        "vehicle_profile" to "گاڑی کا پروفائل",
        "export_pdf" to "پی ڈی ایف رپورٹ بنائیں",
        "share_pdf" to "رپورٹ شیئر کریں",
        "pdf_generated" to "پی ڈی ایف رپورٹ کامیابی سے بن گئی",
        
        "add_document" to "دستاویز شامل کریں",
        "doc_type" to "دستاویز کی قسم",
        "issue_date" to "اجراء کی تاریخ",
        "expiry_date" to "میعاد ختم ہونے کی تاریخ",
        "no_documents" to "کوئی دستاویزات محفوظ نہیں ہیں",

        "emergency_title" to "روڈ سائیڈ ایمرجنسی مدد",
        "one_tap_call" to "ایک ٹیپ سے کال کریں",
        "mechanic" to "مکینک",
        "family" to "اہل خانہ",
        "insurance_hotline" to "انشورنس ہیلپ لائن",
        "towing_service" to "ٹو ٹرک سروس",
        "add_contact" to "ایمرجنسی نمبر شامل کریں",
        "no_contacts" to "کوئی ہنگامی نمبر موجود نہیں",
        
        "achievements_title" to "کامیابیاں اور ایوارڈز",
        "settings_title" to "ایپ سیٹنگز",
        "theme_mode" to "ڈارک موڈ",
        "language" to "زبان کا انتخاب",
        "backup_data" to "بیک اپ لیں (JSON)",
        "restore_data" to "ریسٹور کریں",
        "notifications" to "نوٹیفیکیشنز",
        "about_drivecare" to "ڈرائیو کیئر ورژن 2.0.0",

        "analytics_cost_breakdown" to "اخراجات کا تجزیہ",
        "monthly_fuel_expenditure" to "ماہانہ ایندھن کا خرچ ($)",
        "expense_category_breakdown" to "اخراجات کی اقسام",
        "total_expense_logged" to "کل اخراجات",
        "recent_timeline_activity" to "حالیہ سرگرمیاں",
        "view_all" to "تمام دیکھیں",
        "no_recent_activity" to "ابھی کوئی حالیہ سرگرمی نہیں ہے۔",
        "vehicles_active_fleet" to "فعال گاڑیاں",
        "tasks_pending" to "بقیہ کام",
        "all_tasks_up_to_date" to "تمام کام مکمل ہیں",
        "fleet_health_label" to "گاڑیوں کی صحت",
        "fuel_efficiency" to "ایندھن کی اوسط",
        "cost_label" to "خرچ",

        "insurance_policies_title" to "انشورنس اور پالیسیاں",
        "insurance_policies_sub" to "پالیسی کی تفصیلات اور یاد دہانی",
        "status_active" to "فعال",
        "status_expiring_soon" to "جلد ختم ہونے والی",
        "status_expired" to "ختم شدہ",
        "filter_all" to "تمام",
        "filter_expiring" to "میعاد ختم",
        "no_policies_found" to "کوئی انشورنس پالیسی نہیں ملی",
        "no_policies_desc" to "انشورنس پالیسی شامل کرنے کے لیے نیچے بٹن دبائیں۔",
        "policy_no_prefix" to "پالیسی نمبر",
        "vehicle_linked" to "منسلک گاڑی",
        "coverage_type" to "کوریج کی قسم",
        "premium" to "پریمیم",
        "valid_period" to "میعاد",
        "auto_renew_on" to "آٹو رینیو فعال",
        "btn_renew" to "تجدید کریں",
        "btn_agent" to "ایجنٹ",
        "add_policy_title" to "انشورنس پالیسی شامل کریں",
        "edit_policy_title" to "پالیسی تبدیل کریں",
        "provider_name" to "انشورنس کمپنی کا نام",
        "policy_number" to "پالیسی نمبر",
        "start_date" to "شروعات کی تاریخ",
        "agent_phone" to "ایجنٹ فون نمبر",
        "notes_info" to "نوٹس / اضافی معلومات",
        "enable_autorenew" to "آٹو رینیو کی سچیچ آن کریں",
        "save_policy" to "پالیسی محفوظ کریں",
        "update_policy" to "پالیسی اپ ڈیٹ کریں",
        "renew_policy_title" to "پالیسی کی تجدید کریں #",
        "new_start_date" to "نئی شروعاتی تاریخ",
        "new_expiry_date" to "نئی آخری تاریخ",
        "renewal_premium" to "تجدید کی رقم",
        "confirm_renewal" to "تجدید کی تصدیق اور خرچ درج کریں",
        "delete_policy_title" to "انشورنس پالیسی ختم کریں",

        "expense_manager_title" to "اخراجات کے مینیجر",
        "expense_manager_sub" to "پارکنگ، ٹول، انشورنس اور ٹیکس کا ٹریکر",
        "total_vehicle_expenses" to "گاڑی کے کل اخراجات",
        "category_breakdown" to "اقسام کے اخراجات",
        "expense_history" to "اخراجات کی ہسٹری",
        "no_expenses_found" to "کوئی اخراجات درج نہیں ہیں",
        "no_expenses_desc" to "پارکنگ یا دیگر اخراجات درج کرنے کے لیے بٹن دبائیں۔",
        "add_expense" to "خرچ درج کریں",
        "log_new_expense" to "نیا خرچ درج کریں",
        "expense_title" to "خرچ کی تفصیل",
        "category" to "قسم",
        "amount" to "رقم",
        "date" to "تاریخ",

        "timeline_title" to "گاڑی کی ہسٹری ٹائم لائن",
        "timeline_sub" to "ایندھن، سروس اور اخراجات کا مکمل ریکارڈ",
        "no_timeline_found" to "کوئی ریکارڈ موجود نہیں",

        "gps_title" to "جی پی ایس لائیو ٹریکنگ",
        "gps_sub" to "لائیو لوکیشن اور سفر کا ہسٹری ریکارڈ",

        "family_sharing_title" to "فیملی شیئرنگ اور ڈرائیورز",
        "family_sharing_sub" to "گاڑی کی ملٹی یوزر شیئرنگ",

        "section_management" to "سروسز اور انتظامی امور",
        "section_preferences" to "سیٹنگز اور ٹولز",
        "cloud_account_offline" to "لوکل اکاؤنٹ (آف لائن)",
        "cloud_sync_desc" to "ڈیٹا بیک اپ کے لیے سائن ان کریں",
        "btn_sign_in" to "سائن ان کریں",
        "btn_profile" to "پروفائل",
        "user_profile_title" to "صارف کا پروفائل",
        "cloud_signin_title" to "کلاؤڈ سائن ان",

        "got_it" to "سمجھ گیا",
        "dont_show_again" to "دوبارہ نہ دکھائیں",
        "reset_feature_guides" to "فیچر گائیڈز ری سیٹ کریں",
        "reset_feature_guides_desc" to "تمام خصوصیات کے تعارفی پاپ اپس دوبارہ فعال کریں۔",
        "guides_reset_toast" to "فیچر گائیڈز کامیابی کے ساتھ ری سیٹ ہو گئیں!",
        "guide_main_benefits" to "اہم فوائد اور قابلیتیں",
        "guide_language_selector" to "گائیڈ کی زبان",

        "guide_dashboard_title" to "ڈیش بورڈ کا جائزہ",
        "guide_dashboard_desc" to "آپ کی گاڑیوں کی حالت، اخراجات کے خلاصے اور حالیہ سرگرمیوں کا مرکزی مرکز۔",
        "guide_dashboard_benefits" to "• گاڑیوں کا ہیلتھ اسکور اور فعال گاڑیاں دیکھیں\n• ماہانہ ایندھن اور کل اخراجات کی نگرانی کریں\n• ٹرپ لاگت کا تخمینہ اور ہسٹری دیکھیں",

        "guide_garage_title" to "میری گاڑیاں (گیراج)",
        "guide_garage_desc" to "اپنی گاڑیوں کے پروفائلز، کیلو میٹر ریڈنگ اور ہیلتھ اسٹیٹس کا انتظام کریں۔",
        "guide_garage_benefits" to "• نمبر پلیٹ اور گاڑی کی تفصیلات محفوظ کریں\n• مائلج اور اوڈومیٹر ریڈنگ اپ ڈیٹ کریں\n• پی ڈی ایف رپورٹ بنائیں اور شیئر کریں",

        "guide_fuel_title" to "ایندھن کا ٹریکر",
        "guide_fuel_desc" to "پیٹرول بھروانے کا ریکارڈ رکھیں، مائلج کا حساب لگائیں اور اخراجات دیکھیں۔",
        "guide_fuel_benefits" to "• ایندھن کی اوسط (km/L) ٹریک کریں\n• فی کلو میٹر خرچ کا حساب لگائیں\n• ماہانہ ایندھن کے اخراجات کا تجزیہ کریں",

        "guide_services_title" to "سروس اور مرمت کی ہسٹری",
        "guide_services_desc" to "آئل چینج، بریک سروس اور آئندہ کی مرمت کا مکمل ریکارڈ رکھیں۔",
        "guide_services_benefits" to "• سمارٹ سروس مشیر کی خودکار تجاویز\n• ورکشاپ اور سروس کی تفصیلات محفوظ کریں\n• پارٹس کی تبدیلی کی تاریخ کا ریکارڈ",

        "guide_expenses_title" to "اخراجات کا مینیجر",
        "guide_expenses_desc" to "پارکنگ، ٹول ٹیکس، انشورنس اور دیگر غیر ایندھن اخراجات کا ریکارڈ رکھیں۔",
        "guide_expenses_benefits" to "• پارکنگ، ٹول اور ٹیکسز کی درجہ بندی\n• ہر گاڑی کا الگ خرچ کا جائزہ\n• اخراجات کا گرافکل چارٹ",

        "guide_documents_title" to "گاڑی کی دستاویزات",
        "guide_documents_desc" to "رجسٹریشن، ڈرائیونگ لائسنس اور پرمٹ محفوظ طریقے سے اسٹور کریں۔",
        "guide_documents_benefits" to "• دستاویزات کی آخری تاریخیں محفوظ کریں\n• میعاد ختم ہونے پر الرٹس حاصل کریں\n• ڈیجیٹل کاپیاں ہر وقت دستیاب رکھیں",

        "guide_insurance_title" to "انشورنس پالیسیاں",
        "guide_insurance_desc" to "پالیسی نمبرز، کوریج کی تفصیلات، ایجنٹ نمبر اور رینیول کی تاریخیں دیکھیں۔",
        "guide_insurance_benefits" to "• پالیسی ختم ہونے کے خودکار الرٹس\n• ایک کلک پر تجدید اور خرچ کا اندراج\n• ایجنٹ کو براہ راست کال کرنے کی سہولت",

        "guide_reminders_title" to "سروس کی یاد دہانیاں",
        "guide_reminders_desc" to "آئل چینج، ٹائر چیکنگ اور بیٹری سروس کی تاریخوں کے لیے یاد دہانی سیٹ کریں۔",
        "guide_reminders_benefits" to "• اہم مرمتی کام کبھی مس نہ ہوں\n• اینڈرائڈ سسٹم نوٹیفیکیشنز کے ساتھ منسلک\n• ایک ٹیپ پر کام مکمل مارک کریں",

        "guide_notifications_title" to "نوٹیفیکیشن انجن",
        "guide_notifications_desc" to "بقیہ کاموں اور میعاد ختم ہونے پر بیک گراؤنڈ میں خودکار الرٹس حاصل کریں۔",
        "guide_notifications_benefits" to "• انشورنس اور دستاویزات کے بروقت الرٹس\n• نوٹیفیکیشن کی ترجیحات تبدیل کریں\n• ایپ بند ہونے پر بھی الرٹس حاصل کریں",

        "guide_gps_tracking_title" to "جی پی ایس لائیو ٹریکنگ",
        "guide_gps_tracking_desc" to "گاڑی کی لائیو لوکیشن، جیوفینس الرٹس اور روٹ ہسٹری دیکھیں۔",
        "guide_gps_tracking_benefits" to "• میپ پر لائیو لوکیشن اور اسپیڈ دیکھیں\n• جیوفینس کی حد عبور ہونے پر الرٹس\n• پرانے سفر کا مکمل تجزیہ",

        "guide_family_sharing_title" to "فیملی شیئرنگ اور ڈرائیورز",
        "guide_family_sharing_desc" to "اہل خانہ کے ساتھ گاڑیوں کی رسائی شیئر کریں اور ڈرائیورز کے پروفائلز مینیج کریں۔",
        "guide_family_sharing_benefits" to "• ملٹی یوزر گاڑی کی شیئرنگ\n• ڈرائیور پروفائلز اور فون نمبرز\n• گاڑی کی منتقلی اور چابی ہینڈ اوور",

        "guide_settings_title" to "سیٹنگز اور ترجیحات",
        "guide_settings_desc" to "زبان، کرنسی سمبل، ڈارک موڈ اور ڈیٹا بیک اپ کی سیٹنگز تبدیل کریں۔",
        "guide_settings_benefits" to "• ملٹی کرنسی ($ € £ ₹ ¥) اور زبانیں\n• لائٹ اور ڈارک تھیم\n• JSON ڈیٹا بیک اپ اور ریسٹور"
    )

    private val arabicMap = mapOf(
        "app_name" to "درايف كير",
        "tab_dashboard" to "لوحة التحكم",
        "tab_garage" to "المرأب",
        "tab_fuel" to "الوقود",
        "tab_services" to "الصيانة",
        "tab_service" to "الصيانة",
        "tab_more" to "المزيد",
        "tab_documents" to "الوثائق",
        "tab_emergency" to "الطوارئ",
        "tab_achievements" to "الإنجازات",
        "tab_settings" to "الإعدادات",
        "tab_reminders" to "التذكيرات",
        "backup_restore" to "النسخ الاحتياطي والاستعادة",
        
        "total_vehicles" to "إجمالي المركبات",
        "upcoming_services" to "الصيانة القادمة",
        "active_insurance" to "التأمين النشط",
        "monthly_fuel_cost" to "تكلفة الوقود الشهرية",
        "total_fuel_entries" to "سجلات الوقود",
        "vehicle_health_score" to "مؤشر صحة المركبة",
        
        "health_excellent" to "ممتاز",
        "health_good" to "جيد",
        "health_fair" to "مقبول",
        "health_poor" to "ضعيف",
        
        "add_vehicle" to "إضافة مركبة",
        "edit_vehicle" to "تعديل المركبة",
        "delete_vehicle" to "حذف المركبة",
        "no_vehicles_title" to "لم يتم إضافة مركبات بعد",
        "no_vehicles_desc" to "اضغط على الزر أدناه لإضافة أول مركبة.",
        "vehicle_name" to "اسم المركبة",
        "brand" to "الماركة",
        "model" to "الموديل",
        "year" to "السنة",
        "plate_no" to "رقم لوحة السيارة",
        "fuel_type" to "نوع الوقود",
        "odometer" to "قراءة العداد (كم)",

        "status_active" to "نشط",
        "status_expiring_soon" to "ينتهي قريباً",
        "status_expired" to "منتهي",
        "filter_all" to "الكل",
        "insurance_policies_title" to "التأمين والوثائق",
        "insurance_policies_sub" to "تفاصيل البوليصة والتذكيرات",
        "expense_manager_title" to "إدارة المصاريف",
        "expense_manager_sub" to "متابعة الرسوم والمواقف والتأمين",
        "timeline_title" to "السجل الزمني للمركبة",
        "gps_title" to "تتبع GPS والرحلات",
        "family_sharing_title" to "المشاركة العائلية",
        "section_management" to "الخدمات والإدارة",
        "section_preferences" to "تفضيلات التطبيق والأدوات",
        "cloud_account_offline" to "حساب محلي (غير متصل)",
        "cloud_sync_desc" to "تسجيل الدخول للنسخ الاحتياطي",
        "btn_sign_in" to "تسجيل الدخول",
        "btn_profile" to "الملف الشخصي",
        "user_profile_title" to "الملف الشخصي",
        "cloud_signin_title" to "تسجيل الدخول السحابي",
        "analytics_cost_breakdown" to "تحليل المصاريف",
        "monthly_fuel_expenditure" to "إنفاق الوقود الشهري ($)",
        "expense_category_breakdown" to "توزيع المصاريف حسب الفئة",
        "total_expense_logged" to "إجمالي المصاريف المسجلة",
        "recent_timeline_activity" to "الأنشطة الأخيرة",
        "view_all" to "عرض الكل",
        "no_recent_activity" to "لا توجد أنشطة حديثة مسجلة.",
        "vehicles_active_fleet" to "مركبات نشطة في الأسطول",
        "tasks_pending" to "مهام معلقة",
        "all_tasks_up_to_date" to "جميع المهام مكتملة",

        "got_it" to "فهمت",
        "dont_show_again" to "عدم إظهار المرة القادمة",
        "reset_feature_guides" to "إعادة ضبط أدلة الميزات",
        "reset_feature_guides_desc" to "إعادة تمكين الإرشادات التعريفية لجميع ميزات التطبيق.",
        "guides_reset_toast" to "تم إعادة ضبط أدلة الميزات بنجاح!",
        "guide_main_benefits" to "المزايا والقدرات الرئيسية",
        "guide_language_selector" to "لغة الدليل",

        "guide_dashboard_title" to "نظرة عامة على لوحة التحكم",
        "guide_dashboard_desc" to "مركز التحكم الرئيسي لحالة الأسطول، وملخص المصاريف، والأنشطة الأخيرة.",
        "guide_dashboard_benefits" to "• عرض مؤشر صحة الأسطول والمركبات النشطة\n• متابعة إنفاق الوقود الشهري والمصاريف الكلية\n• حاسبة تكاليف الرحلات والسجل الزمني",

        "guide_garage_title" to "مركباتي (المرأب)",
        "guide_garage_desc" to "إدارة ملفات المركبات، والمواصفات، وقراءات العداد، وحالة الصحة.",
        "guide_garage_benefits" to "• تتبع مواصفات المركبة وأرقام اللوحات\n• تحديث قراءات العداد والمسافات\n• إنشاء ومشاركة تقارير PDF",

        "guide_fuel_title" to "متبع الوقود",
        "guide_fuel_desc" to "تسجيل تعبئة الوقود، وحساب كفاءة الاستهلاك الحقيقية، ومتابعة مصاريف المحطات.",
        "guide_fuel_benefits" to "• تتبع معدل استهلاك الوقود (كم/لتر)\n• متابعة التكلفة لكل كيلومتر\n• تحليل مصاريف الوقود الشهرية",

        "guide_services_title" to "سجل الصيانة",
        "guide_services_desc" to "تسجيل تغيير الزيت، وتدوير الإطارات، وإصلاح الفرامل، ومواعيد الصيانة القادمة.",
        "guide_services_benefits" to "• توصيات الصيانة الذكية من الذكاء الاصطناعي\n• الاحتفاظ بسجلات الورشة والصيانة المفصلة\n• تتبع تاريخ استبدال قطع الغيار",

        "guide_expenses_title" to "مدير المصاريف",
        "guide_expenses_desc" to "تتبع مصاريف المركبة غير الوقود مثل المواقف، والرسوم، والضرائب، والإصلاحات.",
        "guide_expenses_benefits" to "• تصنيف المواقف والرسوم والضرائب للإصلاحات\n• تفصيل المصاريف لكل مركبة\n• رسوم بيانية توضيحية لفئات الإنفاق",

        "guide_documents_title" to "وثائق المركبة",
        "guide_documents_desc" to "حفظ رخص السير، وشهادات الفحص، ورخص القيادة، والتصاريح بآمان.",
        "guide_documents_benefits" to "• حفظ تواريخ الإصدار والانتهاء للوثائق\n• شارات وتنبيهات لانتهاء الصلاحية\n• الوصول الرقمي للوثائق في أي وقت",

        "guide_insurance_title" to "وثائق التأمين",
        "guide_insurance_desc" to "تتبع أرقام الوثائق النشطة، وتفاصيل التغطية، وهواتف الوكلاء، وتواريخ التجديد.",
        "guide_insurance_benefits" to "• تنبيهات تلقائية لانتهاء وثائق التأمين\n• التجديد وتسجيل المصاريف بنقرة واحدة\n• الاتصال المباشر بخط طوارئ الوكيل",

        "guide_reminders_title" to "تذكيرات الصيانة",
        "guide_reminders_desc" to "تعيين مواعيد مخصصة لتغيير الزيت، وفحص الإطارات، والبطارية، والتجديدات.",
        "guide_reminders_benefits" to "• عدم تفويت مهام الصيانة الهامة مطلقاً\n• متكامل مع إشعارات نظام أندرويد\n• تعليم المهام كمكتملة بضغطة واحدة",

        "guide_notifications_title" to "محرك الإشعارات",
        "guide_notifications_desc" to "تنبيهات خلفية تلقائية عبر Android WorkManager للمهام المعلقة.",
        "guide_notifications_benefits" to "• تنبيهات النظام للتأمين والوثائق المنتهية\n• فئات إشعارات قابلة للتخصيص\n• الفحص في الخلفية حتى عند إغلاق التطبيق",

        "guide_gps_tracking_title" to "التتبع المباشر بـ GPS",
        "guide_gps_tracking_desc" to "محاكاة التتبع المباشر لموقع المركبة، وتنبيهات السياج الجغرافي، وسجلات الرحلات.",
        "guide_gps_tracking_benefits" to "• عرض الموقع المباشر والسرعة على الخريطة\n• تنبيهات اختراق حدود السياج الجغرافي\n• تحليل مسار الرحلات السابقة",

        "guide_family_sharing_title" to "المشاركة العائلية والسائقون",
        "guide_family_sharing_desc" to "مشاركة الوصول للمركبة مع أفراد العائلة، وإدارة ملفات السائقين، وتحديد الصلاحيات.",
        "guide_family_sharing_benefits" to "• مشاركة المركبة بين عدة مستخدمين\n• ملفات السائقين ومعلومات الاتصال\n• نقل الملكية والمفاتيح بسهولة",

        "guide_settings_title" to "الإعدادات والتفضيلات",
        "guide_settings_desc" to "تخصيص الوحدات والإقليمية، ورمز العملة، والوضع الليلي، والمزامنة السحابية.",
        "guide_settings_benefits" to "• خيارات العملات ($ € £ ₹ ¥) واللغات المتعددة\n• التبديل بين الوضع المظلم والفاتح\n• نسخ واعادة استعادة البيانات بصيغة JSON"
    )

    private val hindiMap = mapOf(
        "app_name" to "ड्राइवकेयर",
        "tab_dashboard" to "डैशबोर्ड",
        "tab_garage" to "गैरेज",
        "tab_fuel" to "ईंधन",
        "tab_services" to "सर्विस",
        "tab_service" to "सर्विस",
        "tab_more" to "अन्य",
        "tab_documents" to "दस्तावेज़",
        "tab_emergency" to "आपातकालीन सेवा",
        "tab_achievements" to "उपलब्धियां",
        "tab_settings" to "सेटिंग्स",
        "tab_reminders" to "रिमाइंडर",
        "backup_restore" to "बैकअप और रिस्टोर",
        
        "total_vehicles" to "कुल वाहन",
        "upcoming_services" to "आगामी सर्विस",
        "active_insurance" to "सक्रिय बीमा",
        "monthly_fuel_cost" to "मासिक ईंधन खर्च",
        "total_fuel_entries" to "कुल ईंधन लॉग",
        "vehicle_health_score" to "वाहन स्वास्थ्य स्कोर",

        "status_active" to "सक्रिय",
        "status_expiring_soon" to "शीघ्र समाप्त होने वाला",
        "status_expired" to "समाप्त",
        "filter_all" to "सभी",
        "insurance_policies_title" to "बीमा और नीतियां",
        "insurance_policies_sub" to "नीति विवरण और नवीनीकरण रिमाइंडर",
        "expense_manager_title" to "खर्च प्रबंधक",
        "expense_manager_sub" to "पार्किंग, टोल और बीमा खर्च ट्रैक करें",
        "timeline_title" to "वाहन टाइमलाइन",
        "gps_title" to "जीपीएस ट्रैकिंग",
        "family_sharing_title" to "फैमिली शेयरिंग",
        "section_management" to "प्रबंधन और सेवाएं",
        "section_preferences" to "ऐप प्राथमिकताएं और टूल्स",
        "cloud_account_offline" to "स्थानीय खाता (ऑफ़लाइन)",
        "cloud_sync_desc" to "डेटा बैकअप के लिए साइन इन करें",
        "btn_sign_in" to "साइन इन करें",
        "btn_profile" to "प्रोफ़ाइल",
        "user_profile_title" to "उपयोगकर्ता प्रोफ़ाइल",
        "cloud_signin_title" to "क्लाउड साइन इन",
        "analytics_cost_breakdown" to "लागत विश्लेषण",
        "monthly_fuel_expenditure" to "मासिक ईंधन खर्च ($)",
        "expense_category_breakdown" to "श्रेणी के अनुसार खर्च",
        "total_expense_logged" to "कुल दर्ज खर्च",
        "recent_timeline_activity" to "हाल की गतिविधियां",
        "view_all" to "सभी देखें",
        "no_recent_activity" to "कोई हालिया गतिविधि नहीं है।",
        "vehicles_active_fleet" to "सक्रिय वाहन",
        "tasks_pending" to "लंबित कार्य",
        "all_tasks_up_to_date" to "सभी कार्य पूर्ण हैं",

        "got_it" to "समझ गया",
        "dont_show_again" to "पुनः न दिखाएं",
        "reset_feature_guides" to "फ़ीचर गाइड रीसेट करें",
        "reset_feature_guides_desc" to "सभी ऐप सुविधाओं के लिए परिचयात्मक पॉपअप फिर से सक्षम करें।",
        "guides_reset_toast" to "फ़ीचर गाइड सफलतापूर्वक रीसेट हो गए!",
        "guide_main_benefits" to "मुख्य लाभ एवं क्षमताएं",
        "guide_language_selector" to "गाइड भाषा",

        "guide_dashboard_title" to "डैशबोर्ड अवलोकन",
        "guide_dashboard_desc" to "आपके बेड़े की स्थिति, खर्च सारांश और हालिया गतिविधियों का मुख्य केंद्र।",
        "guide_dashboard_benefits" to "• वाहन स्वास्थ्य स्कोर और सक्रिय वाहन देखें\n• मासिक ईंधन और कुल खर्चों की निगरानी करें\n• यात्रा लागत कैलकुलेटर और हालिया टाइमलाइन",

        "guide_garage_title" to "मेरे वाहन (गैरेज)",
        "guide_garage_desc" to "अपने वाहनों के प्रोफाइल, स्पेसिफिकेशन, ओडोमीटर रीडिंग और स्वास्थ्य स्थिति प्रबंधित करें।",
        "guide_garage_benefits" to "• वाहन विवरण और नंबर प्लेट ट्रैक करें\n• माइलेज और ओडोमीटर रीडिंग अपडेट करें\n• पीडीएफ रिपोर्ट बनाएं और साझा करें",

        "guide_fuel_title" to "ईंधन ट्रैकर",
        "guide_fuel_desc" to "ईंधन भरवाने का रिकॉर्ड रखें, वास्तविक माइलेज का हिसाब लगाएं और खर्च देखें।",
        "guide_fuel_benefits" to "• ईंधन खपत (km/L) ट्रैक करें\n• प्रति किलोमीटर लागत की निगरानी करें\n• मासिक ईंधन व्यय का विश्लेषण करें",

        "guide_services_title" to "सर्विस इतिहास",
        "guide_services_desc" to "तेल परिवर्तन, टायर रोटेशन, ब्रेक मरम्मत और आगामी सर्विस शेड्यूल रिकॉर्ड करें।",
        "guide_services_benefits" to "• एआई स्मार्ट रखरखाव सिफारिशें\n• विस्तृत कार्यशाला और सेवा लॉग रखें\n• पुर्जों के प्रतिस्थापन इतिहास को ट्रैक करें",

        "guide_expenses_title" to "खर्च प्रबंधक",
        "guide_expenses_desc" to "पार्किंग, टोल, टैक्स और मरम्मत जैसे गैर-ईंधन खर्चों को ट्रैक करें।",
        "guide_expenses_benefits" to "• पार्किंग, टोल, टैक्स और मरम्मत को वर्गीकृत करें\n• प्रति वाहन खर्च का विवरण\n• दृश्य व्यय श्रेणी प्रगति चार्ट",

        "guide_documents_title" to "वाहन दस्तावेज़",
        "guide_documents_desc" to "पंजीकरण प्रमाण पत्र, ड्राइविंग लाइसेंस और परमिट सुरक्षित रूप से संग्रहीत करें।",
        "guide_documents_benefits" to "• दस्तावेजों के जारी होने और समाप्ति तिथि सहेजें\n• समाप्ति चेतावनी बैज और अलर्ट\n• यात्रा के दौरान डिजिटल दस्तावेज़ों तक पहुँच",

        "guide_insurance_title" to "बीमा नीतियां",
        "guide_insurance_desc" to "सक्रिय नीति संख्या, कवरेज विवरण, एजेंट हेल्पलाइन और नवीनीकरण तिथियां ट्रैक करें।",
        "guide_insurance_benefits" to "• स्वचालित बीमा समाप्ति चेतावनियां\n• एक-टैप नवीनीकरण और खर्च लॉगिंग\n• एजेंट हेल्पलाइन पर सीधे कॉल करें",

        "guide_reminders_title" to "सर्विस रिमाइंडर",
        "guide_reminders_desc" to "तेल परिवर्तन, टायर निरीक्षण, बैटरी जांच और नवीनीकरण के लिए रिमाइंडर्स सेट करें।",
        "guide_reminders_benefits" to "• कभी भी महत्वपूर्ण रखरखाव कार्य न भूलें\n• एंड्रॉइड सिस्टम नोटिफिकेशन के साथ एकीकृत\n• त्वरित कार्य पूर्ण स्थिति दर्ज करें",

        "guide_notifications_title" to "नोटिफिकेशन इंजन",
        "guide_notifications_desc" to "लंबित कार्यों के लिए एंड्रॉइड वर्कमैनेजर के माध्यम से स्वचालित पृष्ठभूमि अलर्ट।",
        "guide_notifications_benefits" to "• समाप्त हो रहे बीमा और दस्तावेजों के लिए सिस्टम अलर्ट\n• अनुकूलन योग्य अधिसूचना श्रेणियां\n• ऐप बंद होने पर भी बैकग्राउंड चेक",

        "guide_gps_tracking_title" to "जीपीएस लाइव ट्रैकिंग",
        "guide_gps_tracking_desc" to "लाइव वाहन स्थान ट्रैकिंग, जियोफेंस अलर्ट और यात्रा मार्ग लॉग का अनुकरण करें।",
        "guide_gps_tracking_benefits" to "• मानचित्र पर लाइव स्थान और गति देखें\n• जियोफेंस सीमा उल्लंघन अलर्ट\n• ऐतिहासिक यात्रा मार्ग विश्लेषण",

        "guide_family_sharing_title" to "फैमिली शेयरिंग और ड्राइवर्स",
        "guide_family_sharing_desc" to "परिवार के सदस्यों के साथ वाहन की पहुंच साझा करें, ड्राइवर प्रोफाइल प्रबंधित करें।",
        "guide_family_sharing_benefits" to "• बहु-उपयोगकर्ता वाहन साझाकरण\n• ड्राइवर प्रोफाइल और संपर्क विवरण\n• निर्बाध स्वामित्व और कुंजी स्थानांतरण",

        "guide_settings_title" to "सेटिंग्स और प्राथमिकताएं",
        "guide_settings_desc" to "क्षेत्रीय इकाइयों, मुद्रा प्रतीकों, थीम मोड और क्लाउड डेटाबेस सिंक को कस्टमाइज़ करें।",
        "guide_settings_benefits" to "• बहु-मुद्रा ($ € £ ₹ ¥) और भाषा विकल्प\n• लाइट और डार्क थीम प्राथमिकताएं\n• JSON डेटा बैकअप और रिस्टोर"
    )

    private val chineseMap = mapOf(
        "app_name" to "DriveCare 驭管家",
        "tab_dashboard" to "仪表盘",
        "tab_garage" to "我的车库",
        "tab_fuel" to "油耗",
        "tab_services" to "保养",
        "tab_service" to "保养",
        "tab_more" to "更多",
        "tab_documents" to "车辆证件",
        "tab_emergency" to "紧急救援",
        "tab_achievements" to "里程成就",
        "tab_settings" to "设置",
        "tab_reminders" to "提醒事项",
        "backup_restore" to "备份与恢复",
        
        "total_vehicles" to "车辆总数",
        "upcoming_services" to "待办保养",
        "active_insurance" to "有效保险",
        "monthly_fuel_cost" to "本月燃油支出",
        "total_fuel_entries" to "加油记录总数",
        "vehicle_health_score" to "车辆健康指数",

        "status_active" to "有效",
        "status_expiring_soon" to "即将到期",
        "status_expired" to "已过期",
        "filter_all" to "全部",
        "insurance_policies_title" to "车辆保险",
        "insurance_policies_sub" to "保单详情、续保提醒与保障跟踪",
        "expense_manager_title" to "费用管理",
        "expense_manager_sub" to "记录停车、高速费、税费与维修费用",
        "timeline_title" to "车辆时间线",
        "gps_title" to "GPS 实时定位与行程",
        "family_sharing_title" to "家庭与共享驾驶员",
        "section_management" to "管理与服务",
        "section_preferences" to "应用偏好与工具",
        "cloud_account_offline" to "本地账户 (离线)",
        "cloud_sync_desc" to "登录以同步数据与多端备份",
        "btn_sign_in" to "登录",
        "btn_profile" to "个人资料",
        "user_profile_title" to "个人资料",
        "cloud_signin_title" to "云端账户登录",
        "analytics_cost_breakdown" to "费用分析与统计",
        "monthly_fuel_expenditure" to "每月燃油支出 ($)",
        "expense_category_breakdown" to "费用类别明细",
        "total_expense_logged" to "已记录总费用",
        "recent_timeline_activity" to "近期动态",
        "view_all" to "查看全部",
        "no_recent_activity" to "暂无近期动态记录。",
        "vehicles_active_fleet" to "车队活跃车辆",
        "tasks_pending" to "项待办任务",
        "all_tasks_up_to_date" to "所有任务均已最新",

        "got_it" to "知道了",
        "dont_show_again" to "不再显示",
        "reset_feature_guides" to "重置功能指南",
        "reset_feature_guides_desc" to "重新启用所有应用功能的首次介绍弹窗。",
        "guides_reset_toast" to "功能介绍指南已成功重置！",
        "guide_main_benefits" to "核心优势与功能",
        "guide_language_selector" to "指南语言",

        "guide_dashboard_title" to "仪表盘总览",
        "guide_dashboard_desc" to "您的车辆状态、费用汇总和近期动态的核心控制中心。",
        "guide_dashboard_benefits" to "• 查看车队健康指数与活跃车辆\n• 监控每月油耗与总支出\n• 使用行程费用预估与近期动态",

        "guide_garage_title" to "我的车辆（车库）",
        "guide_garage_desc" to "管理您的车辆档案、技术参数、里程表读数与健康状态。",
        "guide_garage_benefits" to "• 追踪车辆参数与车牌信息\n• 更新里程表读数\n• 生成并分享 PDF 车辆报告",

        "guide_fuel_title" to "油耗追踪",
        "guide_fuel_desc" to "记录加油日志、计算真实油耗 (km/L) 并监控加油站支出。",
        "guide_fuel_benefits" to "• 追踪燃油效率 (km/L)\n• 监控每公里行车成本\n• 分析每月加油站支出分析",

        "guide_services_title" to "保养记录",
        "guide_services_desc" to "记录更换机油、轮胎对调、刹车维修及未来保养计划。",
        "guide_services_benefits" to "• AI 智能保养建议\n• 详细记录修理厂与服务日志\n• 追踪零部件更换历史",

        "guide_expenses_title" to "费用管理",
        "guide_expenses_desc" to "追踪非加油类车辆开支，如停车费、高速费、税费与维修费。",
        "guide_expenses_benefits" to "• 分类整理停车、高速、税费与维修\n• 按车辆拆分支出明细\n• 可视化支出类别比例图表",

        "guide_documents_title" to "车辆证件",
        "guide_documents_desc" to "安全存储行驶证、驾驶证、环保标志与各类许可等。",
        "guide_documents_benefits" to "• 保存证件签发与到期日期\n• 到期预警标识与提醒\n• 随时随地查阅电子版证件",

        "guide_insurance_title" to "车辆保险",
        "guide_insurance_desc" to "追踪在保保单号、保障范围、保险专员电话与续保日期。",
        "guide_insurance_benefits" to "• 保单到期自动预警\n• 一键续保并自动计入费用\n• 一键拨打保险代理热线",

        "guide_reminders_title" to "提醒事项",
        "guide_reminders_desc" to "针对换油、轮胎检查、蓄电池检测与各种到期设定自定义提醒。",
        "guide_reminders_benefits" to "• 绝不错过关键车辆保养\n• 深度集成 Android 系统通知栏\n• 一键标记已完成状态",

        "guide_notifications_title" to "通知推送引擎",
        "guide_notifications_desc" to "通过 Android WorkManager 后台定时推送待办事项与预警。",
        "guide_notifications_benefits" to "• 保险与证件到期的系统级推送\n• 可自定义通知分类与开关\n• 应用关闭状态下依然后台监测",

        "guide_gps_tracking_title" to "GPS 实时定位",
        "guide_gps_tracking_desc" to "模拟车辆实时位置追踪、电子围栏预警与历史行程轨迹。",
        "guide_gps_tracking_benefits" to "• 地图实时查看车速与当前位置\n• 越界电子围栏触发报警\n• 历史行程路线深度分析",

        "guide_family_sharing_title" to "家庭与共享驾驶员",
        "guide_family_sharing_desc" to "与家庭成员共享车辆使用权、管理驾驶员档案并分配权限。",
        "guide_family_sharing_benefits" to "• 多用户共同管理车辆\n• 驾驶员档案与紧急联系方式\n• 无缝车辆转让与电子钥匙交接",

        "guide_settings_title" to "设置与偏好",
        "guide_settings_desc" to "自定义计量单位、货币符号、主题模式与云端数据库同步。",
        "guide_settings_benefits" to "• 多国货币 ($ € £ ₹ ¥) 与多语言切换\n• 明亮与深色主题模式切换\n• JSON 数据一键备份与还原"
    )
}
