package com.drivecare.app.utils

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import com.drivecare.app.data.model.FuelEntry
import com.drivecare.app.data.model.Maintenance
import com.drivecare.app.data.model.Vehicle
import java.io.File
import java.io.FileOutputStream

object PdfReportGenerator {

    fun generateAndShareReport(
        context: Context,
        vehicle: Vehicle,
        healthScore: Int,
        fuelEntries: List<FuelEntry>,
        maintenanceLogs: List<Maintenance>
    ): File? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val prefs = context.getSharedPreferences("drivecare_prefs", Context.MODE_PRIVATE)
        val langCode = prefs.getString("selected_language", AppLanguage.ENGLISH.code) ?: AppLanguage.ENGLISH.code
        val lang = AppLanguage.entries.find { it.code == langCode } ?: AppLanguage.ENGLISH

        val paint = Paint()
        val titlePaint = Paint()
        val subTitlePaint = Paint()

        // Background
        canvas.drawColor(Color.WHITE)

        // Header Background
        paint.color = Color.rgb(24, 119, 242)
        canvas.drawRect(0f, 0f, 595f, 100f, paint)

        // Title
        titlePaint.color = Color.WHITE
        titlePaint.textSize = 24f
        titlePaint.isFakeBoldText = true
        canvas.drawText("${AppStrings.get("app_name", lang)} Vehicle Report", 30f, 50f, titlePaint)

        subTitlePaint.color = Color.WHITE
        subTitlePaint.textSize = 12f
        canvas.drawText("${vehicle.vehicleName} (${vehicle.brand} ${vehicle.model} - ${vehicle.registrationNumber})", 30f, 75f, subTitlePaint)

        // Content Paint
        paint.color = Color.BLACK
        paint.textSize = 14f
        paint.isFakeBoldText = true

        var y = 140f

        // Vehicle Summary Box
        canvas.drawText(AppStrings.get("vehicle_profile", lang), 30f, y, paint)
        y += 20f

        paint.isFakeBoldText = false
        paint.textSize = 11f
        canvas.drawText("${AppStrings.get("type", lang)}: ${vehicle.vehicleType} | ${AppStrings.get("year", lang)}: ${vehicle.manufacturingYear} | ${AppStrings.get("fuel_type", lang)}: ${vehicle.fuelType}", 30f, y, paint)
        y += 18f
        canvas.drawText("${AppStrings.get("odometer", lang)}: ${vehicle.odometerReading} km | ${AppStrings.get("plate_no", lang)}: ${vehicle.registrationNumber}", 30f, y, paint)
        y += 18f
        canvas.drawText("${AppStrings.get("vehicle_health_score", lang)}: $healthScore / 100", 30f, y, paint)
        y += 35f

        // Fuel Summary
        paint.isFakeBoldText = true
        paint.textSize = 14f
        canvas.drawText("${AppStrings.get("tab_fuel", lang)} (${fuelEntries.size})", 30f, y, paint)
        y += 20f

        paint.isFakeBoldText = false
        paint.textSize = 10f
        if (fuelEntries.isEmpty()) {
            canvas.drawText(AppStrings.get("no_fuel_entries", lang), 30f, y, paint)
            y += 20f
        } else {
            fuelEntries.take(8).forEach { entry ->
                canvas.drawText("${entry.fuelDate} - ${entry.fuelQuantity} L @ \$${entry.amountPaid} (${entry.fuelStationName.ifBlank { "Station N/A" }})", 30f, y, paint)
                y += 16f
            }
        }
        y += 15f

        // Maintenance Summary
        paint.isFakeBoldText = true
        paint.textSize = 14f
        canvas.drawText("${AppStrings.get("tab_services", lang)} (${maintenanceLogs.size})", 30f, y, paint)
        y += 20f

        paint.isFakeBoldText = false
        paint.textSize = 10f
        if (maintenanceLogs.isEmpty()) {
            canvas.drawText(AppStrings.get("no_service_logs", lang), 30f, y, paint)
            y += 20f
        } else {
            maintenanceLogs.take(8).forEach { log ->
                canvas.drawText("${log.serviceDate} - ${log.serviceTitle} | Cost: \$${log.serviceCost} (${log.workshopName.ifBlank { "Workshop N/A" }})", 30f, y, paint)
                y += 16f
            }
        }

        // Footer
        paint.color = Color.GRAY
        paint.textSize = 9f
        canvas.drawText("Generated by DriveCare - Worldwide Vehicle Management App", 30f, 810f, paint)

        pdfDocument.finishPage(page)

        val reportsDir = File(context.cacheDir, "reports")
        if (!reportsDir.exists()) reportsDir.mkdirs()
        val file = File(reportsDir, "DriveCare_${vehicle.vehicleName.replace(" ", "_")}_Report.pdf")

        try {
            pdfDocument.writeTo(FileOutputStream(file))
            pdfDocument.close()

            val uri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(shareIntent, "Share Vehicle PDF Report"))

            return file
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            return null
        }
    }
}
